using NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD = UnityEngine.Rigidbody;
using WHATTHEFUCKISORANGES_NAMEDAFTERTHEFRUITORTHECOLOR_TIMESENSITIVEPLEASERESPOND = BWChaos.Effects.EffectBase;
using HAHAHAFUCKYOUFORTHINKINGYOUDBEABLETOLOOKATTHETYPENAMES_YOUCANHOLDTHISLFORTHATONEPLAYA = UnityEngine.GameObject;
using QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT = StressLevelZero.AI.AIBrain;
using WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM = BWChaos.GlobalVariables;
using IWENTTOSIXFLAGSYESTERDAYRIGHT_ANDINTHELINEFORARIDETHEREWASTHISGROUPANDINTHATGROUPTHEREWASAGUYTHATLOOKEDLIKEHESAWLILNASXANDWASLIKEYEAHIWANTTOLOOKLIKETHAT_HEHADABISEXUALPRIDEFLAGONHISHEARTLOCKETTHINGANDINLINEHIMANDHISGROUPWERETALKINGABOUTSTUFFTHEYDDONETOGETHERANDTHEYSAIDTHEYHADANORGY_PRETTYFUCKINGWILDRIGHT_THATSTHETYPEOFPEOPLETHATGOTOMAGICMOUNTAINIGUESS = System.Collections.IEnumerator;
using ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE = UnityEngine.WaitForSecondsRealtime;
using RNJESUS_NOTROCKSTAR_BECAUSEIMNOTTAKETWOINTERACTIVE_IMEXTRAES_CAMKNOWSMEASCHESMOND = UnityEngine.WaitForFixedUpdate;
using https__cdn_discordapp_com_attachments_587792632986730507_870901103141740547_Rockstar_mp4 = MelonLoader.MelonCoroutines;
using YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE = ModThatIsNotMod.Player;
using NEVERBUYNOGASSTATIONWEED_IWOKEUPANDALLMYCODEWENTFROMCSHARPTOVISUALBASIC_THATDUDEGOTHISBOTTOMSHELFLOUDPACKFROMTHEFUCKINDOLLARSTOREANDSOLDITTOMEFOR20DOLLARS_FUCKTHATSHIT = UnityEngine.Random;
using WHYDOIEVENFUCKINGBOTHERDOINGANYTHINGATTHISPOINT_WHYDONTIJUSTGOTOSLEEPSOIDONTFEELANYTHING_ATLEASTTHENMYUNCONSCIOUSBRAINCANFIGURESHITOUT = BWChaos.Chaos;

namespace BWChaos.Effects
{
    internal class ChesmondEffect : WHATTHEFUCKISORANGES_NAMEDAFTERTHEFRUITORTHECOLOR_TIMESENSITIVEPLEASERESPOND
    {
        public ChesmondEffect() : base("Chesmond Effect", 90) { }
        private string NOBODYFUCKINGREADSTHISSHITANYWAY_ANDNOBODYEVENUSESTHEENTANGLEMENTMODULE_WHYDOIEVENBOTHER = "__player";
        private object BLAMETREVFORTHIS_ISAIDIWOULDPUSHCHESMONDOBFUSCATIONTOMAIN_HESAIDIWOULDNT_ANDHEREWEARE;
        override public void OnEffectStart()
        {
            BLAMETREVFORTHIS_ISAIDIWOULDPUSHCHESMONDOBFUSCATIONTOMAIN_HESAIDIWOULDNT_ANDHEREWEARE = https__cdn_discordapp_com_attachments_587792632986730507_870901103141740547_Rockstar_mp4.Start(CHESMONDTOURGUIDEBOOKLET_BETTERTHANGOINGTOCANCUN_SOURCE_DUDETRUSTME_IVETOTALLYBEENTOCANCUNBEFORE_UHHUHYEAHUHHUHUHHUH());
        }

        public override void OnEffectEnd()
        {
            https__cdn_discordapp_com_attachments_587792632986730507_870901103141740547_Rockstar_mp4.Stop(BLAMETREVFORTHIS_ISAIDIWOULDPUSHCHESMONDOBFUSCATIONTOMAIN_HESAIDIWOULDNT_ANDHEREWEARE);
            WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbFeet.useGravity = true;
            WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.useGravity = true;
            WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbKnee.useGravity = true;
            WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbPelvis.useGravity = true;
            YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.leftHand.rb.useGravity = true;
            YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.rightHand.rb.useGravity = true;
        }
        
        public override void HandleNetworkMessage(string https___discord_com_channels__me_401874001246421014_922058213241798686_CALLTHATMYHEARTIN13KCHARS_FUCKINGHATEFEELINGLIKETHIS_BUTDISTRACTMYSELFWITHPROGRAMMING_GOD_FUCK)
        {
            if (https___discord_com_channels__me_401874001246421014_922058213241798686_CALLTHATMYHEARTIN13KCHARS_FUCKINGHATEFEELINGLIKETHIS_BUTDISTRACTMYSELFWITHPROGRAMMING_GOD_FUCK == NOBODYFUCKINGREADSTHISSHITANYWAY_ANDNOBODYEVENUSESTHEENTANGLEMENTMODULE_WHYDOIEVENBOTHER)
            {
                WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbFeet.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbFeet.useGravity;
                WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.useGravity;
                WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbKnee.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbKnee.useGravity;
                WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbPelvis.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbPelvis.useGravity;
                YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.leftHand.rb.useGravity = !YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.leftHand.rb.useGravity;
                YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.rightHand.rb.useGravity = !YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.rightHand.rb.useGravity;
            }
            else
            {
                HAHAHAFUCKYOUFORTHINKINGYOUDBEABLETOLOOKATTHETYPENAMES_YOUCANHOLDTHISLFORTHATONEPLAYA FUCKINGPOUREDMYHEARTOUT_GOTA_ICAREABOUTYOUDEEPLY_IGETTHATBUTFUCKINGWHATDOESTHATDOFORMYACHINGHEART_SOHEREIAM_VENTINGOVERFUCKINGCSHARP = HAHAHAFUCKYOUFORTHINKINGYOUDBEABLETOLOOKATTHETYPENAMES_YOUCANHOLDTHISLFORTHATONEPLAYA.Find(https___discord_com_channels__me_401874001246421014_922058213241798686_CALLTHATMYHEARTIN13KCHARS_FUCKINGHATEFEELINGLIKETHIS_BUTDISTRACTMYSELFWITHPROGRAMMING_GOD_FUCK);
                if (FUCKINGPOUREDMYHEARTOUT_GOTA_ICAREABOUTYOUDEEPLY_IGETTHATBUTFUCKINGWHATDOESTHATDOFORMYACHINGHEART_SOHEREIAM_VENTINGOVERFUCKINGCSHARP == null)
                {
                    WHYDOIEVENFUCKINGBOTHERDOINGANYTHINGATTHISPOINT_WHYDONTIJUSTGOTOSLEEPSOIDONTFEELANYTHING_ATLEASTTHENMYUNCONSCIOUSBRAINCANFIGURESHITOUT.Warn("AIBrain object not found in client - " + https___discord_com_channels__me_401874001246421014_922058213241798686_CALLTHATMYHEARTIN13KCHARS_FUCKINGHATEFEELINGLIKETHIS_BUTDISTRACTMYSELFWITHPROGRAMMING_GOD_FUCK);
                    return;
                }

                QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT DAILYAGONYBEATSWHAT_NOTHING_FUCKINGNOTHING_IWISHIHADCOMPLETECONTROLOVERMYEMOTIONS_GUESSILLSETTLEFORFORCINGMYSELFTOHAVENOEMOTIONS_HASHTAGHUSKLIFEAMIRIGHT = FUCKINGPOUREDMYHEARTOUT_GOTA_ICAREABOUTYOUDEEPLY_IGETTHATBUTFUCKINGWHATDOESTHATDOFORMYACHINGHEART_SOHEREIAM_VENTINGOVERFUCKINGCSHARP.GetComponent<QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT>();
                if (DAILYAGONYBEATSWHAT_NOTHING_FUCKINGNOTHING_IWISHIHADCOMPLETECONTROLOVERMYEMOTIONS_GUESSILLSETTLEFORFORCINGMYSELFTOHAVENOEMOTIONS_HASHTAGHUSKLIFEAMIRIGHT == null)
                {
                    WHYDOIEVENFUCKINGBOTHERDOINGANYTHINGATTHISPOINT_WHYDONTIJUSTGOTOSLEEPSOIDONTFEELANYTHING_ATLEASTTHENMYUNCONSCIOUSBRAINCANFIGURESHITOUT.Warn("AIBrain component not found in client - " + https___discord_com_channels__me_401874001246421014_922058213241798686_CALLTHATMYHEARTIN13KCHARS_FUCKINGHATEFEELINGLIKETHIS_BUTDISTRACTMYSELFWITHPROGRAMMING_GOD_FUCK);
                    return;
                }

                foreach (NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD IHOPETHATONEDAYITDOESNTHURTMETOTALKTOYOU_OREVENKNOWTHATYOUEXIST_THISHURTSANDITHURTSBAD_BUTITHINKYOULLBEFINE_THATWHATTHEYREFORRIGHT_ASHOULDERTOCRYON_FUCKDOIHAVE_SOMEPEOPLETHATIKNOWSUPERFICIALLYANDIVEONLYOPENEDUPTOINTHEPASTTWOWEEKS in DAILYAGONYBEATSWHAT_NOTHING_FUCKINGNOTHING_IWISHIHADCOMPLETECONTROLOVERMYEMOTIONS_GUESSILLSETTLEFORFORCINGMYSELFTOHAVENOEMOTIONS_HASHTAGHUSKLIFEAMIRIGHT._rigidbodies)
                {
                    IHOPETHATONEDAYITDOESNTHURTMETOTALKTOYOU_OREVENKNOWTHATYOUEXIST_THISHURTSANDITHURTSBAD_BUTITHINKYOULLBEFINE_THATWHATTHEYREFORRIGHT_ASHOULDERTOCRYON_FUCKDOIHAVE_SOMEPEOPLETHATIKNOWSUPERFICIALLYANDIVEONLYOPENEDUPTOINTHEPASTTWOWEEKS.useGravity = !IHOPETHATONEDAYITDOESNTHURTMETOTALKTOYOU_OREVENKNOWTHATYOUEXIST_THISHURTSANDITHURTSBAD_BUTITHINKYOULLBEFINE_THATWHATTHEYREFORRIGHT_ASHOULDERTOCRYON_FUCKDOIHAVE_SOMEPEOPLETHATIKNOWSUPERFICIALLYANDIVEONLYOPENEDUPTOINTHEPASTTWOWEEKS.useGravity;
                }
            }
        }

        private IWENTTOSIXFLAGSYESTERDAYRIGHT_ANDINTHELINEFORARIDETHEREWASTHISGROUPANDINTHATGROUPTHEREWASAGUYTHATLOOKEDLIKEHESAWLILNASXANDWASLIKEYEAHIWANTTOLOOKLIKETHAT_HEHADABISEXUALPRIDEFLAGONHISHEARTLOCKETTHINGANDINLINEHIMANDHISGROUPWERETALKINGABOUTSTUFFTHEYDDONETOGETHERANDTHEYSAIDTHEYHADANORGY_PRETTYFUCKINGWILDRIGHT_THATSTHETYPEOFPEOPLETHATGOTOMAGICMOUNTAINIGUESS CHESMONDTOURGUIDEBOOKLET_BETTERTHANGOINGTOCANCUN_SOURCE_DUDETRUSTME_IVETOTALLYBEENTOCANCUNBEFORE_UHHUHYEAHUHHUHUHHUH()
        {
            if (isNetworked) yield break;
            yield return null;
            while (Active) {
                foreach (QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT ADDITIONOPERATOR_THATSPLUSINCSHARP_BUTINLISPITSBEGINPARENTHESESPLUSTHENASPACEFOLLOWEDBYTHENUMBERSYOUWANTTOSUMSEPARATEDBYSPACESTHENENDINGPARENTHESES in UnityEngine.Object.FindObjectsOfType<QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT>())
                {
                    if (NEVERBUYNOGASSTATIONWEED_IWOKEUPANDALLMYCODEWENTFROMCSHARPTOVISUALBASIC_THATDUDEGOTHISBOTTOMSHELFLOUDPACKFROMTHEFUCKINDOLLARSTOREANDSOLDITTOMEFOR20DOLLARS_FUCKTHATSHIT.value > 0.5f) continue; // Only make some npc's float. why? idk, felt like it.
                    SendNetworkData(ADDITIONOPERATOR_THATSPLUSINCSHARP_BUTINLISPITSBEGINPARENTHESESPLUSTHENASPACEFOLLOWEDBYTHENUMBERSYOUWANTTOSUMSEPARATEDBYSPACESTHENENDINGPARENTHESES.transform.GetFullPath());
                    foreach (NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD MYFAVORITEGAMERGIRL_YUP_POKIMANE_FIRSTIGETTHEBAGTHENIGETTHEWETBRAIN in ADDITIONOPERATOR_THATSPLUSINCSHARP_BUTINLISPITSBEGINPARENTHESESPLUSTHENASPACEFOLLOWEDBYTHENUMBERSYOUWANTTOSUMSEPARATEDBYSPACESTHENENDINGPARENTHESES._rigidbodies)
                    {
                        MYFAVORITEGAMERGIRL_YUP_POKIMANE_FIRSTIGETTHEBAGTHENIGETTHEWETBRAIN.useGravity = !MYFAVORITEGAMERGIRL_YUP_POKIMANE_FIRSTIGETTHEBAGTHENIGETTHEWETBRAIN.useGravity;
                    }
                    yield return new RNJESUS_NOTROCKSTAR_BECAUSEIMNOTTAKETWOINTERACTIVE_IMEXTRAES_CAMKNOWSMEASCHESMOND();
                }
                if (NEVERBUYNOGASSTATIONWEED_IWOKEUPANDALLMYCODEWENTFROMCSHARPTOVISUALBASIC_THATDUDEGOTHISBOTTOMSHELFLOUDPACKFROMTHEFUCKINDOLLARSTOREANDSOLDITTOMEFOR20DOLLARS_FUCKTHATSHIT.value > 0.25f)
                {
                    SendNetworkData(NOBODYFUCKINGREADSTHISSHITANYWAY_ANDNOBODYEVENUSESTHEENTANGLEMENTMODULE_WHYDOIEVENBOTHER);
                    WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbFeet.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbFeet.useGravity;
                    WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.useGravity;
                    WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbKnee.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbKnee.useGravity;
                    WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbPelvis.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbPelvis.useGravity;
                    YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.leftHand.rb.useGravity = !YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.leftHand.rb.useGravity;
                    YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.rightHand.rb.useGravity = !YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.rightHand.rb.useGravity;
                }
                yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(NEVERBUYNOGASSTATIONWEED_IWOKEUPANDALLMYCODEWENTFROMCSHARPTOVISUALBASIC_THATDUDEGOTHISBOTTOMSHELFLOUDPACKFROMTHEFUCKINDOLLARSTOREANDSOLDITTOMEFOR20DOLLARS_FUCKTHATSHIT.RandomRange(5,10));
            }
        }

    }

    
}