using NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD = UnityEngine.Rigidbody;
using WHATTHEFUCKISORANGES_NAMEDAFTERTHEFRUITORTHECOLOR_TIMESENSITIVEPLEASERESPOND = BWChaos.Effects.EffectBase;
using HAHAHAFUCKYOUFORTHINKINGYOUDBEABLETOLOOKATTHETYPENAMES_YOUCANHOLDTHISLFORTHATONEPLAYA = UnityEngine.GameObject;
using QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT = StressLevelZero.AI.AIBrain;
using WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM = BWChaos.GlobalVariables;
using IWENTTOSIXFLAGSYESTERDAYRIGHT_ANDINTHELINEFORARIDETHEREWASTHISGROUPANDINTHATGROUPTHEREWASAGUYTHATLOOKEDLIKEHESAWLILNASXANDWASLIKEYEAHIWANTTOLOOKLIKETHAT_HEHADABISEXUALPRIDEFLAGONHISHEARTLOCKETTHINGANDINLINEHIMANDHISGROUPWERETALKINGABOUTSTUFFTHEYDDONETOGETHERANDTHEYSAIDTHEYHADANORGY_PRETTYFUCKINGWILDRIGHT_THATSTHETYPEOFPEOPLETHATGOTOMAGICMOUNTAINIGUESS = System.Collections.IEnumerator;
using ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE = UnityEngine.WaitForSecondsRealtime;
using RNJESUS_NOTROCKSTAR_BECAUSEIMNOTTAKETWOINTERACTIVE_IMEXTRAES_CAMKNOWSMEASCHESMOND = UnityEngine.WaitForFixedUpdate;
using https__cdn_discordapp_com_attachments_587792632986730507_870901103141740547_Rockstar_mp4 = MelonLoader.MelonCoroutines;
using YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE = ModThatIsNotMod.Player;

namespace BWChaos.Effects
{
    internal class ChesmondEffect : WHATTHEFUCKISORANGES_NAMEDAFTERTHEFRUITORTHECOLOR_TIMESENSITIVEPLEASERESPOND
    {
        public ChesmondEffect() : base("Chesmond Effect", 120) { }

        private object BLAMETREVFORTHIS_ISAIDIWOULDPUSHCHESMONDOBFUSCATIONTOMAIN_HESAIDIWOULDNT_ANDHEREWEARE;
        override public void OnEffectStart()
        {
            BLAMETREVFORTHIS_ISAIDIWOULDPUSHCHESMONDOBFUSCATIONTOMAIN_HESAIDIWOULDNT_ANDHEREWEARE = https__cdn_discordapp_com_attachments_587792632986730507_870901103141740547_Rockstar_mp4.Start(CHESMONDTOURGUIDEBOOKLET_BETTERTHANGOINGTOCANCUN_SOURCE_DUDETRUSTME_IVETOTALLYBEENTOCANCUNBEFORE_UHHUHYEAHUHHUHUHHUH());
        }

        public override void OnEffectEnd()
        {
            https__cdn_discordapp_com_attachments_587792632986730507_870901103141740547_Rockstar_mp4.Stop(BLAMETREVFORTHIS_ISAIDIWOULDPUSHCHESMONDOBFUSCATIONTOMAIN_HESAIDIWOULDNT_ANDHEREWEARE);
        }

        private IWENTTOSIXFLAGSYESTERDAYRIGHT_ANDINTHELINEFORARIDETHEREWASTHISGROUPANDINTHATGROUPTHEREWASAGUYTHATLOOKEDLIKEHESAWLILNASXANDWASLIKEYEAHIWANTTOLOOKLIKETHAT_HEHADABISEXUALPRIDEFLAGONHISHEARTLOCKETTHINGANDINLINEHIMANDHISGROUPWERETALKINGABOUTSTUFFTHEYDDONETOGETHERANDTHEYSAIDTHEYHADANORGY_PRETTYFUCKINGWILDRIGHT_THATSTHETYPEOFPEOPLETHATGOTOMAGICMOUNTAINIGUESS CHESMONDTOURGUIDEBOOKLET_BETTERTHANGOINGTOCANCUN_SOURCE_DUDETRUSTME_IVETOTALLYBEENTOCANCUNBEFORE_UHHUHYEAHUHHUHUHHUH()
        {
            yield return null;
            while (Active) {
                foreach (QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT ADDITIONOPERATOR_THATSPLUSINCSHARP_BUTINLISPITSBEGINPARENTHESESPLUSTHENASPACEFOLLOWEDBYTHENUMBERSYOUWANTTOSUMSEPARATEDBYSPACESTHENENDINGPARENTHESES in HAHAHAFUCKYOUFORTHINKINGYOUDBEABLETOLOOKATTHETYPENAMES_YOUCANHOLDTHISLFORTHATONEPLAYA.FindObjectsOfType<StressLevelZero.AI.AIBrain>())
                {
                    if (UnityEngine.Random.value > 0.5f) continue; // Only make some npc's float. why? idk, felt like it.
                    foreach (NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD MYFAVORITEGAMERGIRL_YUP_POKIMANE_FIRSTIGETTHEBAGTHENIGETTHEWETBRAIN in ADDITIONOPERATOR_THATSPLUSINCSHARP_BUTINLISPITSBEGINPARENTHESESPLUSTHENASPACEFOLLOWEDBYTHENUMBERSYOUWANTTOSUMSEPARATEDBYSPACESTHENENDINGPARENTHESES._rigidbodies) MYFAVORITEGAMERGIRL_YUP_POKIMANE_FIRSTIGETTHEBAGTHENIGETTHEWETBRAIN.useGravity = !MYFAVORITEGAMERGIRL_YUP_POKIMANE_FIRSTIGETTHEBAGTHENIGETTHEWETBRAIN.useGravity;
                    yield return new RNJESUS_NOTROCKSTAR_BECAUSEIMNOTTAKETWOINTERACTIVE_IMEXTRAES_CAMKNOWSMEASCHESMOND();
                }
                if (UnityEngine.Random.value > 0.25f)
                {
                    WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbFeet.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbFeet.useGravity;
                    WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.useGravity;
                    WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbKnee.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbKnee.useGravity;
                    WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbPelvis.useGravity = !WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbPelvis.useGravity;
                    YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.leftHand.rb.useGravity = !YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.leftHand.rb.useGravity;
                    YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.rightHand.rb.useGravity = !YOUALREADYKNOWWHOITIS_ITSYABOIEREREAHAAHA_WOOFWOOFWOOF_CHRIIIIIIIIS_ANDIMCOOLWITHTHEJUICE_ANDIVEGOTMAJORJUICE.rightHand.rb.useGravity;
                }
                yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(UnityEngine.Random.RandomRange(5,10));
            }
        }

    }

    
}