using NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD = UnityEngine.Vector3;
using WHATTHEFUCKISORANGES_NAMEDAFTERTHEFRUITORTHECOLOR_TIMESENSITIVEPLEASERESPOND = BWChaos.Effects.EffectBase;
using HAHAHAFUCKYOUFORTHINKINGYOUDBEABLETOLOOKATTHETYPENAMES_YOUCANHOLDTHISLFORTHATONEPLAYA = UnityEngine.GameObject;
using QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT = UnityEngine.Quaternion;
using ADDITIONOPERATOR_THATSPLUSINCSHARP_BUTINLISPITSBEGINPARENTHESESPLUSTHENASPACEFOLLOWEDBYTHENUMBERSYOUWANTTOSUMSEPARATEDBYSPACESTHENENDINGPARENTHESES = ModThatIsNotMod.RandomShit.AdManager;
using WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM = BWChaos.GlobalVariables;
using IWENTTOSIXFLAGSYESTERDAYRIGHT_ANDINTHELINEFORARIDETHEREWASTHISGROUPANDINTHATGROUPTHEREWASAGUYTHATLOOKEDLIKEHESAWLILNASXANDWASLIKEYEAHIWANTTOLOOKLIKETHAT_HEHADABISEXUALPRIDEFLAGONHISHEARTLOCKETTHINGANDINLINEHIMANDHISGROUPWERETALKINGABOUTSTUFFTHEYDDONETOGETHERANDTHEYSAIDTHEYHADANORGY_PRETTYFUCKINGWILDRIGHT_THATSTHETYPEOFPEOPLETHATGOTOMAGICMOUNTAINIGUESS = System.Collections.IEnumerator;
using ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE = UnityEngine.WaitForSecondsRealtime;
using BLAMETREVFORTHIS = UnityEngine.UI.Text;
using RNJESUS_NOTROCKSTAR_BECAUSEIMNOTTAKETWOINTERACTIVE_IMEXTRAES_CAMKNOWSMEASCHESMOND = UnityEngine.WaitForFixedUpdate;
using https__cdn_discordapp_com_attachments_587792632986730507_870901103141740547_Rockstar_mp4 = MelonLoader.MelonCoroutines;

namespace BWChaos.Effects
{
    internal class ChesmondEffect : WHATTHEFUCKISORANGES_NAMEDAFTERTHEFRUITORTHECOLOR_TIMESENSITIVEPLEASERESPOND
    {
        public ChesmondEffect() : base("Chesmond Effect", 120) { }

        private NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD NUMBERSEVEN_STUDENTWATCHESPORN_ANDGETSNAYKID;
        //private float FLOATLIKETHETHROATGOAT_IMNOTGAYISWEAR_IDKWHATTHATISBUTITRHYMED_CALLMEABONAFIDESONGWRITER = 0.0000000000000000000000000000000000000000000000000000000000000000000000000000f;
        private string GOODEVENINGCHAT_SIGNEDCRITIKAL_AKAPENGUINZ0_THEMADMANHIMSELFWITHTHEMOBYHUGE = "HI IM CHESMOND ILL BE YOUR GUIDE FOR TODAY :DDDDDD".ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString().ToString();
        private BLAMETREVFORTHIS KEXT_LIKEFROMMACOS_CAUSEKERNELEXTENTIONISSHORTENEDTOKEXT_IMGONNABEHONESTIDONTKNOWWHATSDIFFERENTBETWEENAKEXTANDALINUXKERNELMODULE;
        override public void OnEffectStart()
        {
            // OK SO BASICLY
            KEXT_LIKEFROMMACOS_CAUSEKERNELEXTENTIONISSHORTENEDTOKEXT_IMGONNABEHONESTIDONTKNOWWHATSDIFFERENTBETWEENAKEXTANDALINUXKERNELMODULE = WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.WristChaosUI.GetComponent<BLAMETREVFORTHIS>();

            https__cdn_discordapp_com_attachments_587792632986730507_870901103141740547_Rockstar_mp4.Start(CHESMONDTOURGUIDEBOOKLET_BETTERTHANGOINGTOCANCUN_SOURCE_DUDETRUSTME_IVETOTALLYBEENTOCANCUNBEFORE_UHHUHYEAHUHHUHUHHUH());
        }

        override public void OnEffectUpdate()
        {
            KEXT_LIKEFROMMACOS_CAUSEKERNELEXTENTIONISSHORTENEDTOKEXT_IMGONNABEHONESTIDONTKNOWWHATSDIFFERENTBETWEENAKEXTANDALINUXKERNELMODULE.text = GOODEVENINGCHAT_SIGNEDCRITIKAL_AKAPENGUINZ0_THEMADMANHIMSELFWITHTHEMOBYHUGE; //hopefully this runs between the chaosui updating and the screen being drawn
            NUMBERSEVEN_STUDENTWATCHESPORN_ANDGETSNAYKID = WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.transform.forward;
        }

        private HAHAHAFUCKYOUFORTHINKINGYOUDBEABLETOLOOKATTHETYPENAMES_YOUCANHOLDTHISLFORTHATONEPLAYA DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(string NOVARIABLELEFTBEHIND_ALLVARIABLES_ALLPROPERTIES_ALLFIELDS_WILLBERENAMED_WILLBEOBFUSCATED_WITHCHESMONDOBFUSCATION)
        {
            var YEEAWEOUTCHEAITTHE_GOT_DAMDASHCAM_YOUALREADYKNOWWHOITIS = ADDITIONOPERATOR_THATSPLUSINCSHARP_BUTINLISPITSBEGINPARENTHESESPLUSTHENASPACEFOLLOWEDBYTHENUMBERSYOUWANTTOSUMSEPARATEDBYSPACESTHENENDINGPARENTHESES.CreateNewAd(NOVARIABLELEFTBEHIND_ALLVARIABLES_ALLPROPERTIES_ALLFIELDS_WILLBERENAMED_WILLBEOBFUSCATED_WITHCHESMONDOBFUSCATION);
            var IPITYTHEFOOLTHATTRIESTOREADTHISCODETOUNDERSTANDWHATTHEFUCKITDOES_BUTFUCKIT_ITISWHATITIS_EETEEZWHATEETEEZ = WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.rbHead.transform.gameObject.transform.gameObject.transform.gameObject.transform.gameObject.transform;
            YEEAWEOUTCHEAITTHE_GOT_DAMDASHCAM_YOUALREADYKNOWWHOITIS.transform.transform.transform.transform.position = (IPITYTHEFOOLTHATTRIESTOREADTHISCODETOUNDERSTANDWHATTHEFUCKITDOES_BUTFUCKIT_ITISWHATITIS_EETEEZWHATEETEEZ.position.normalized * IPITYTHEFOOLTHATTRIESTOREADTHISCODETOUNDERSTANDWHATTHEFUCKITDOES_BUTFUCKIT_ITISWHATITIS_EETEEZWHATEETEEZ.position.magnitude) + IPITYTHEFOOLTHATTRIESTOREADTHISCODETOUNDERSTANDWHATTHEFUCKITDOES_BUTFUCKIT_ITISWHATITIS_EETEEZWHATEETEEZ.forward.normalized.normalized.normalized.normalized.normalized.normalized.normalized.normalized.normalized.normalized.normalized;
            YEEAWEOUTCHEAITTHE_GOT_DAMDASHCAM_YOUALREADYKNOWWHOITIS.transform.transform.transform.transform.transform.transform.transform.transform.transform.transform.transform.transform.transform.rotation = QUAINT_LIKETHATYOINKYSPLOINKY_THATGLOUPYSOUPY_THATSEXUALHARASSMENTCASE_FOUGHTANDLOST_HERLNOTMINE_STILLKEEPINGTHECHILDSUPPORT.LookRotation(YEEAWEOUTCHEAITTHE_GOT_DAMDASHCAM_YOUALREADYKNOWWHOITIS.transform.position - IPITYTHEFOOLTHATTRIESTOREADTHISCODETOUNDERSTANDWHATTHEFUCKITDOES_BUTFUCKIT_ITISWHATITIS_EETEEZWHATEETEEZ.position);
            return YEEAWEOUTCHEAITTHE_GOT_DAMDASHCAM_YOUALREADYKNOWWHOITIS.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject.gameObject;
        }

        private IWENTTOSIXFLAGSYESTERDAYRIGHT_ANDINTHELINEFORARIDETHEREWASTHISGROUPANDINTHATGROUPTHEREWASAGUYTHATLOOKEDLIKEHESAWLILNASXANDWASLIKEYEAHIWANTTOLOOKLIKETHAT_HEHADABISEXUALPRIDEFLAGONHISHEARTLOCKETTHINGANDINLINEHIMANDHISGROUPWERETALKINGABOUTSTUFFTHEYDDONETOGETHERANDTHEYSAIDTHEYHADANORGY_PRETTYFUCKINGWILDRIGHT_THATSTHETYPEOFPEOPLETHATGOTOMAGICMOUNTAINIGUESS CHESMONDTOURGUIDEBOOKLET_BETTERTHANGOINGTOCANCUN_SOURCE_DUDETRUSTME_IVETOTALLYBEENTOCANCUNBEFORE_UHHUHYEAHUHHUHUHHUH ()
        {
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            GOODEVENINGCHAT_SIGNEDCRITIKAL_AKAPENGUINZ0_THEMADMANHIMSELFWITHTHEMOBYHUGE += "\nID LIKE TO TAKE YOU ON A MAGIC CARPET RIDE :DDDDD".ToString().ToString().ToString().ToString().ToString().ToString();
            var HAVEYOUEVERTRIEDWHOLEGRAINBREADITSFARBETTERFORYOU = 1000;
            var YESTERDAYIWENTTOSIXFLAGS_THEWORDOFTHEDAYWAS_BOZO_BOZONE_AND_BOZONELAYER  = new NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD(0, 1, 0);
            for (int i = 0; i < HAVEYOUEVERTRIEDWHOLEGRAINBREADITSFARBETTERFORYOU; i++)
            {
                WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.AddVelocityChange(NUMBERSEVEN_STUDENTWATCHESPORN_ANDGETSNAYKID / 4 + (YESTERDAYIWENTTOSIXFLAGS_THEWORDOFTHEDAYWAS_BOZO_BOZONE_AND_BOZONELAYER  / (HAVEYOUEVERTRIEDWHOLEGRAINBREADITSFARBETTERFORYOU / 2)) * (i - HAVEYOUEVERTRIEDWHOLEGRAINBREADITSFARBETTERFORYOU / 2));
                yield return new RNJESUS_NOTROCKSTAR_BECAUSEIMNOTTAKETWOINTERACTIVE_IMEXTRAES_CAMKNOWSMEASCHESMOND();
            }
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(NOVARIABLELEFTBEHIND_ALLVARIABLES_ALLPROPERTIES_ALLFIELDS_WILLBERENAMED_WILLBEOBFUSCATED_WITHCHESMONDOBFUSCATION: new string(new char[] { 'i', ' ', 'd', 'i', 'd', 'n', 't', ' ', 'k', 'n', 'o', 'w', ' ', 'w', 'h', 'a', 't', ' ', 't', 'o', ' ', 'd', 'o', ' ', 'f', 'o', 'r', ' ', 't', 'h', 'i', 's', ' ', 'e', 'f', 'f', 'e', 'c', 't', }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(NOVARIABLELEFTBEHIND_ALLVARIABLES_ALLPROPERTIES_ALLFIELDS_WILLBERENAMED_WILLBEOBFUSCATED_WITHCHESMONDOBFUSCATION: new string(new char[] { 's', 'o', ' ', 'i', 'l', 'l', ' ', 'p', 'r', 'e', 's', 'e', 'n', 't', ' ', 'a', ' ', 'h', 'i', 's', 't', 'o', 'r', 'y', ' ', 'o', 'f', ' ', 'b', 'w', ' ', 'c', 'h', 'a', 'o', 's', }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(new string(new char[] {
                'a',
                't',
                ' ',
                'f',
                'i',
                'r',
                's',
                't',
                ',',
                ' ',
                'i',
                ' ',
                'd',
                'i',
                'd',
                'n',
                't',
                ' ',
                'k',
                'n',
                'o',
                'w',
                ' ',
                'w',
                'h',
                'a',
                't',
                ' ',
                't',
                'h',
                'e',
                ' ',
                'f',
                'u',
                'c',
                'k',
                ' ',
                't',
                'o',
                ' ',
                'd',
                'o',
                ' ',
                'i',
                'n',
                ' ',
                'v',
                'i',
                's',
                'u',
                'a',
                'l',
                ' ',
                's',
                't',
                'u',
                'd',
                'i',
                'o',
                ' ',
                'i',
                'n',
                ' ',
                'o',
                'r',
                'd',
                'e',
                'r',
                ' ',
                't',
                'o',
                ' ',
                'g',
                'e',
                't',
                ' ',
                'a',
                ' ',
                'm',
                'o',
                'd',
                ' ',
                'i',
                'n',
                ' ',
                'b',
                'o',
                'n',
                'e',
                'w',
                'o',
                'r',
                'k',
                's', //EXPANDEDCAUSEFUCKYOU
            }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(new string(new char[] {
                          'i',
                            ' ',
                              'a',
                                'l',
                                 's',
                                  'o',
                                   ' ',
                                    'd',
                                    'i',
                                    'd',
                                   'n',
                                  't',
                                 ' ',
                               'k',
                             'n',
                           'o',
                         'w',
                       ' ',
                      'h',
                    'o',
                  'w',
                 ' ',
                't',
                'o',
                ' ',
                'w',
                 'o',
                  'r',
                    'k',
                     ' ',
                       'v',
                         's',
                           '2',
                             '0',
                               '1',
                                 '9',
                                  ' ',
                                   'o',
                                    'r',
                                    ' ',
                                    'd',
                                   'o',
                                   ' ',
                                 't',
                                'h',
                              'i',
                            'n',
                          'g',
                        's',
                      ' ',
                     'l',
                   'i',
                  'k',
                 'e',
                ' ',
                'a',
                'd',
                 'd',
                  'i',
                   'n',
                     'g',
                      ' ',
                        'r',
                          'e',
                            'f',
                              'e',
                                'r',
                                 'e',
                                   'n',
                                   'c',
                                    'e',
                                    's',
                                    ',',
                                   ' ',
                                  's',
                                 'o',
                               ' ',
                             'w',
                           'h',
                         'e',
                       'n',
                     ' ',
                    'm',
                  'a',
                 'k',
                'i',
                'n',
                'g',
                 ' ',
                 '"',
                  't',
                    'h',
                      'e',
                        ' ',
                          'f',
                           'u',
                             'n',
                               'n',
                                 'y',
                                  '"',
                                   ' ',
                                    'i',
                                    ' ',
                                    'b',
                                   'e',
                                  'c',
                                 'a',
                                'm',
                              'e',
                            ' ',
                          'a',
                        ' ',
                      'r',
                    'e',
                   's',
                  'i',
                 'd',
                'e',
                'n',
                't',
                 ' ',
                  'o',
                   'f',
                     ' ',
                       'm',
                         'o',
                           'd',
                             '-',
                               'h',
                                'e',
                                  'l',
                                   'p', // WORM!!!!!!!!!!!!!
            }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(new string(new char[] {
                          'a',
                             'f',
                               't',
                                  'e',
                                   'r',
                                     ' ',
                                      'g',
                                        'e',
                                        't',
                                         't',
                                        'i',
                                        'n',
                                       'g',
                                      ' ',
                                    'a',
                                   ' ',
                                 's',
                                'u',
                               'b',
                              's',
                            't',
                            'a',
                           'n',
                            't',
                            'i',
                             'a',
                              'l',
                                ' ',
                                  'a',
                                    'm',
                                      'o',
                                         'u',
                                           'n',
                                              't',
                                                ' ',
                                                   'o',
                                                    'f',
                                                      ' ',
                                                       'h',
                                                        'e',
                                                        'l',
                                                        'p',
                                                        ' ',
                                                       'f',
                                                      'r',
                                                     'o',
                                                   'm',
                                                  ' ',
                                                't',
                                               'r',
                                              'e',
                                             'v',
                                            ',',
                                            ' ',
                                           'i',
                                            ' ',
                                            'r',
                                              'e',
                                               'l',
                                                 'e',
                                                   'a',
                                                     's',
                                                       'e',
                                                          'd',
                                                            ' ',
                                                               't',
                                                                 'h',
                                                                   'e',
                                                                     ' ',
                                                                      'f',
                                                                       'u',
                                                                        'n',
                                                                        'n',
                                                                        'y',
                                                                       ',',
                                                                       ' ',
                                                                     'a',
                                                                    'n',
                                                                  'd',
                                                                 ' ',
                                                               't',
                                                              'o',
                                                             'o',
                                                            'k',
                                                           ' ',
                                                           'o',
                                                           'n',
                                                            ' ',
                                                             'b',
                                                              'w',
                                                               ' ',
                                                                  'c',
                                                                    'h',
                                                                       'a',
                                                                         'o',
                                                                           's',
                                                                             ' ',
                                                                                'w',
                                                                                  'i',
                                                                                    't',
                                                                                     'h',
                                                                                       ' ',
                                                                                       'n',
                                                                                        'o',
                                                                                       ' ',
                                                                                       'k',
                                                                                      'n',
                                                                                      'o',
                                                                                    'w',
                                                                                   'l',
                                                                                 'e',
                                                                                'd',
                                                                              'g',
                                                                             'e',
                                                                            ' ',
                                                                            'o',
                                                                           'f',
                                                                           ' ',
                                                                           's',
                                                                            'c',
                                                                             'r',
                                                                               'i',
                                                                                'p',
                                                                                   't',
                                                                                     'i',
                                                                                        'n',
                                                                                          'g',
                                                                                             ' ',
                                                                                               'u',
                                                                                                 'n',
                                                                                                   'i',
                                                                                                     't',
                                                                                                      'y',
                                                                                                       ',',
                                                                                                       ' ',
                                                                                                        'a',
                                                                                                       'n',
                                                                                                       'd',
                                                                                                     ' ',
                                                                                                     'l',
                                                                                                   'i',
                                                                                                  't',
                                                                                                't',
                                                                                               'l',
                                                                                             'e',
                                                                                            ' ',
                                                                                           'k',
                                                                                           'n',
                                                                                          'o',
                                                                                           'w',
                                                                                           'l',
                                                                                             'e',
                                                                                              'd',
                                                                                                'g',
                                                                                                 'e',
                                                                                                    ' ',
                                                                                                      'o',
                                                                                                         'f',
                                                                                                           ' ',
                                                                                                              'c',
                                                                                                                's',
                                                                                                                  'h',
                                                                                                                   'a',
                                                                                                                     'r',
                                                                                                                      'p', //WORMDIAGONAL!
            }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(new string(new char[] {

                                                        'i',
                                                                'n',
                                                                      ' ',
                                                                          't',
                                                                            'h',
                                                                          'e',
                                                                     ' ',
                                                              'f',
                                                       'i',
                                                'r',
                                          's',
                                      't',
                                     ' ',
                                       'b',
                                            'a',
                                                   't',
                                                          'c',
                                                                 'h',
                                                                      ' ',
                                                                          'o',
                                                                          'f',
                                                                       ' ',
                                                                  'e',
                                                            'f',
                                                     'f',
                                              'e',
                                          'c',
                                       't',
                                       's',
                                          ',',
                                               ' ',
                                                     'I',
                                                            ' ',
                                                                  'h',
                                                                      'a',
                                                                        'd',
                                                                        ' ',
                                                                     'm',
                                                                'a',
                                                          'g',
                                                   'a',
                                              'z',
                                          'i',
                                        'n',
                                         'e',
                                            ' ',
                                                 'e',
                                                       'j',
                                                             'e',
                                                                  'c',
                                                                      't',
                                                                       'i',
                                                                      'o',
                                                                  'n',
                                                              ',',
                                                        ' ',
                                                  'h',
                                              'e',
                                           'l',
                                          'd',
                                           ' ',
                                               'i',
                                                   't',
                                                         'e',
                                                              'm',
                                                                  ' ',
                                                                     'd',
                                                                     'r',
                                                                    'o',
                                                                'p',
                                                            'p',
                                                      'i',
                                                  'n',
                                              'g',
                                            ',',
                                            ' ',
                                             'f',
                                                 'l',
                                                     'i',
                                                          'n',
                                                               'g',
                                                                  'i',
                                                                    'n',
                                                                   'g',
                                                                 ' ',
                                                              'e',
                                                          'v',
                                                     'e',
                                                 'r',
                                              'y',
                                             't',
                                             'h',
                                                'i',
                                                   'n',
                                                       'g',
                                                           ',',
                                                               ' ',
                                                                 'a',
                                                                  'n',
                                                                  'd',
                                                               ' ',
                                                            'f',
                                                        'l',
                                                     'i',
                                                 'n',
                                               'g',
                                               'i',
                                               'n',
                                                  'g',
                                                     ' ',
                                                        't',
                                                            'h',
                                                              'e',
                                                                ' ',
                                                                 'p',
                                                                'l',
                                                              'a',
                                                           'y',
                                                       'e',
                                                    'r',
                                                  '.',
                                                ' ',
                                                'o',
                                                 'f',
                                                   ' ',
                                                      'c',
                                                         'o',
                                                            'u',
                                                              'r',
                                                               's',
                                                               'e',
                                                              ' ',
                                                            'a',
                                                         ' ',
                                                       'f',
                                                    'e',
                                                   'w',
                                                  ' ',
                                                  'd',
                                                   'i',
                                                     'd',
                                                       'n',
                                                         't',
                                                           ' ',
                                                             'w',
                                                             'o',
                                                             'r',
                                                            'k',
                                                          ' ',
                                                        'l',
                                                      'i',
                                                     'k',
                                                    'e',
                                                   ' ',
                                                    't',
                                                     'h',
                                                      'e',
                                                        'y',
                                                          ' ',
                                                           'd',
                                                            'o',
                                                            ' ',
                                                            'n',
                                                           'o',
                                                         'w',
                                                        ',',
                                                       ' ',
                                                      'b',
                                                     'u',
                                                     't',
                                                     ' ',
                                                      'I',
                                                       ' ',
                                                        'e',
                                                         'v',
                                                          'e',
                                                          'n',
                                                          't',
                                                          'u',
                                                         'a',
                                                         'l',
                                                        'l',
                                                       'y',
                                                       ' ',
                                                      'g',
                                                       'o',
                                                       't',
                                                       ' ',
                                                        't',
                                                        'h',
                                                         'e',
                                                         'm',
                                                         ' ',
                                                         't',
                                                        'o',
                                                        ' ',
                                                        'w',
                                                        'o',
                                                        'r',
                                                        'k',
            }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO("actually, i can give you a taste of those right now");
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            WEDOALITTLETROLLINGLIKEOURFATHERSBEFOREUSANDOURFOREFATHERSBEFORETHEM.Player_PhysBody.AddVelocityChange(new NOMATTERWHATWEBREED_WESTILLAREMADEOFSEED_THISISMYKINGDOMCUM_THISMYKINGDOMCUM_WHENYOUFEELMYD_LOOKINTOMYASS_ITSHWEREMYSEMENHIDE_ITSWHEREMYPENISHARD(0, 25, 10));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            ModThatIsNotMod.Player.GetObjectInHand(ModThatIsNotMod.Player.leftHand)?.GetComponent<StressLevelZero.Interaction.InteractableHost>()?.Drop();
            ModThatIsNotMod.Player.GetObjectInHand(ModThatIsNotMod.Player.rightHand)?.GetComponent<StressLevelZero.Interaction.InteractableHost>()?.Drop();
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            ModThatIsNotMod.Player.GetGunInHand(ModThatIsNotMod.Player.leftHand)?.magazineSocket?.MagazineRelease();
            ModThatIsNotMod.Player.GetGunInHand(ModThatIsNotMod.Player.rightHand)?.magazineSocket?.MagazineRelease(); // NO USING LOL
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(new string(new char[] {
                                                'a',
                                                'f',
                                                't',
                                                'e',
                                                 'r',
                                                 ' ',
                                                 'd',
                                                'w',
                                                'e',
                                                'l',
                                               'l',
                                               'i',
                                               'n',
                                               'g',
                                               ' ',
                                                'o',
                                                'n',
                                                 ' ',
                                                  't',
                                                  'h',
                                                  'e',
                                                  ' ',
                                                 'l',
                                                 'e',
                                                'g',
                                               'a',
                                              'c',
                                              'y',
                                             ' ',
                                              'b',
                                               'r',
                                                'a',
                                                 'n',
                                                  'c',
                                                   'h',
                                                    ' ',
                                                    'f',
                                                   'o',
                                                  'r',
                                                 ' ',
                                               'a',
                                              'b',
                                            'o',
                                            'u',
                                            't',
                                             ' ',
                                              'a',
                                                ' ',
                                                  'm',
                                                    'o',
                                                     'n',
                                                     't',
                                                     'h',
                                                    ',',
                                                  ' ',
                                                'i',
                                              ' ',
                                            'r',
                                           'e',
                                          'l',
                                           'e',
                                            'a',
                                              's',
                                                 'e',
                                                   'd',
                                                     ' ',
                                                      't',
                                                       'h',
                                                      'e',
                                                     ' ',
                                                  'm',
                                               'o',
                                             'd',
                                          ' ',
                                         'a',
                                         'n',
                                          'd',
                                            ' ',
                                               'd',
                                                  'i',
                                                     'd',
                                                       ' ',
                                                        'a',
                                                        ' ',
                                                       'f',
                                                     'e',
                                                  'w',
                                              ' ',
                                           'b',
                                         'u',
                                       'g',
                                       ' ',
                                         'f',
                                            'i',
                                               'x',
                                                   'e',
                                                      's',
                                                         ' ',
                                                          'b',
                                                          'e',
                                                        'f',
                                                     'o',
                                                 'r',
                                             'e',
                                         ' ',
                                       's',
                                      'w',
                                      'i',
                                         't',
                                            'c',
                                                'h',
                                                     'i',
                                                        'n',
                                                           'g',
                                                            ' ',
                                                           't',
                                                        'o',
                                                    ' ',
                                               't',
                                           'r',
                                       'e',
                                     'v',
                                    's',
                                     ' ',
                                         'r',
                                             'e',
                                                  'w',
                                                       'r',
                                                          'i',
                                                             't',
                                                             'e',
                                                           ' ',
                                                        'b',
                                                   'r',
                                              'a',
                                         'n',
                                     'c',
                                   'h',
                                   ' ',
                                     'a',
                                         'n',
                                              'd',
                                                    ' ',
                                                         'a',
                                                             'd',
                                                               'd',
                                                              'i',
                                                            'n',
                                                       'g',
                                                  ' ',
                                            'n',
                                      'e',
                                   'w',
                                 ' ',
                                  'e',
                                     'f',
                                          'f',
                                                'e',
                                                      'c',
                                                           't',
                                                               's',
            }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(new string(new char[] {
                'a',
                 'n',
                  'd',
                   ' ',
                    'h',
                     'e',
                      'r',
                       'e',
                        ' ',
                         'w',
                          'e',
                           ' ',
                            'a',
                             'r',
                              'e',
                               ' ',
                                't',
                                 'o',
                                  'd',
                                   'a',
                                    'y',
                                     ',',
                                      ' ',
                                       'w',
                                        'i',
                                         't',
                                          'h',
                                           ' ',
                                            'a',
                                             ' ',
                                              'p',
                                               'r',
                                                'o',
                                                 'b',
                                                  'a',
                                                   'b',
                                                    'l',
                                                     'y',
                                                      ' ',
                                                       'f',
                                                        'u',
                                                         'n',
                                                          'c',
                                                           't',
                                                            'i',
                                                             'o',
                                                              'n',
                                                               'a',
                                                                'l',
                                                                 ' ',
                                                                  'm',
                                                                   'o',
                                                                    'd',
                                                                     ' ',
                                                                      'a',
                                                                       'n',
                                                                        'd',
                                                                         ' ',
                                                                          'a',
                                                                           ' ',
                                                                            'p',
                                                                             'u',
                                                                              'b',
                                                                               'l',
                                                                                'i',
                                                                                 'c',
                                                                                  ' ',
                                                                                   'g',
                                                                                    'i',
                                                                                     't',
                                                                                      'h',
                                                                                       'u',
                                                                                        'b',
                                                                                         ' ',
                                                                                          'r',
                                                                                           'e',
                                                                                            'p',
                                                                                             'o',
            }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO(new string(new char[] {

                'I',
                                                                                                                                                                                                                        ' ',
                  'g',
                                                                                                                                                                                                                      'l',
                    'o',
                                                                                                                                                                                                                    's',
                      's',
                                                                                                                                                                                                                  'e',
                        'd',
                                                                                                                                                                                                                ' ',
                          'o',
                                                                                                                                                                                                              'v',
                            'e',
                                                                                                                                                                                                            'r',
                              ' ',
                                                                                                                                                                                                          'a',
                                ' ',
                                                                                                                                                                                                        'l',
                                  'o',
                                                                                                                                                                                                      't',
                                    ',',
                                                                                                                                                                                                    ' ',
                                      'b',
                                                                                                                                                                                                  'u',
                                        't',
                                                                                                                                                                                                ' ',
                                          'r',
                                                                                                                                                                                              'e',
                                            'm',
                                                                                                                                                                                            'e',
                                              'm',
                                                                                                                                                                                          'b',
                                                'e',
                                                                                                                                                                                        'r',
                                                  ' ',
                                                                                                                                                                                      't',
                                                    'o',
                                                                                                                                                                                    ' ',
                                                      't',
                                                                                                                                                                                  'h',
                                                        'a',
                                                                                                                                                                                'n',
                                                          'k',
                                                                                                                                                                              ' ',
                                                            't',
                                                                                                                                                                            'r',
                                                              'e',
                                                                                                                                                                          'v',
                                                                ' ',
                                                                                                                                                                        'i',
                                                                  'n',
                                                                                                                                                                      ' ',
                                                                    'm',
                                                                                                                                                                    'o',
                                                                      'd',
                                                                                                                                                                  '-',
                                                                        'g',
                                                                                                                                                                'e',
                                                                          'n',
                                                                                                                                                              'e',
                                                                            'r',
                                                                                                                                                            'a',
                                                                              'l',
                                                                                                                                                          ' ',
                                                                                'f',
                                                                                                                                                        'o',
                                                                                  'r',
                                                                                                                                                      ' ',
                                                                                    'm',
                                                                                                                                                    'a',
                                                                                      'k',
                                                                                                                                                  'i',
                                                                                        'n',
                                                                                                                                                'g',
                                                                                          ' ',
                                                                                                                                              't',
                                                                                            'h',
                                                                                                                                            'i',
                                                                                              's',
                                                                                                                                          ' ',
                                                                                                'p',
                                                                                                                                        'o',
                                                                                                  's',
                                                                                                                                      's',
                                                                                                    'i',
                                                                                                                                    'b',
                                                                                                      'l',
                                                                                                                                  'e',
                                                                                                        ',',
                                                                                                                                ' ',
                                                                                                          'h',
                                                                                                                              'e',
                                                                                                            ' ',
                                                                                                                            'd',
                                                                                                              'e',
                                                                                                                          'a',
                                                                                                                'l',
                                                                                                                        't',
                                                                                                                  ' ',
                                                                                                                      'w',
                                                                                                                    'i',
                                                                                                                    't',
                                                                                                                      'h',
                                                                                                                  ' ',
                                                                                                                        'm',
                                                                                                                'y',
                                                                                                                          ' ',
                                                                                                              'f',
                                                                                                                            'u',
                                                                                                            'c',
                                                                                                                              'k',
                                                                                                          'e',
                                                                                                                                'r',
                                                                                                        'y',
                                                                                                                                  ' ',
                                                                                                      'i',
                                                                                                                                    'n',
                                                                                                    ' ',
                                                                                                                                      't',
                                                                                                  'h',
                                                                                                                                        'e',
                                                                                                ' ',
                                                                                                                                          'b',
                                                                                              'e',
                                                                                                                                            'g',
                                                                                            'i',
                                                                                                                                              'n',
                                                                                          'n',
                                                                                                                                                'i',
                                                                                        'n',
                                                                                                                                                  'g',
                                                                                      ' ',
                                                                                                                                                    'a',
                                                                                    'n',
                                                                                                                                                      'd',
                                                                                  ' ',
                                                                                                                                                        'r',
                                                                                'e',
                                                                                                                                                          'w',
                                                                              'r',
                                                                                                                                                            'o',
                                                                            't',
                                                                                                                                                              'e',
                                                                          ' ',
                                                                                                                                                                't',
                                                                        'h',
                                                                                                                                                                  'e',
                                                                      ' ',
                                                                                                                                                                    'm',
                                                                    'o',
                                                                                                                                                                      'd',
                                                                  ' ',
                                                                                                                                                                        'f',
                                                                'r',
                                                                                                                                                                          'o',
                                                              'm',
                                                                                                                                                                            ' ',
                                                            's',
                                                                                                                                                                              'c',
                                                          'r',
                                                                                                                                                                                'a',
                                                        't',
                                                                                                                                                                                  'c',
                                                      'h',
                                                                                                                                                                                    ',',
                                                    ' ',
                                                                                                                                                                                      'e',
                                                  'l',
                                                                                                                                                                                        'i',
                                                'm',
                                                                                                                                                                                          'i',
                                              'n',
                                                                                                                                                                                            'a',
                                            't',
                                                                                                                                                                                              'i',
                                          'n',
                                                                                                                                                                                                'g',
                                        ' ',
                                                                                                                                                                                                  'a',
                                      ' ',
                                                                                                                                                                                                    'l',
                                    'o',
                                                                                                                                                                                                      't',
                                  ' ',
                                                                                                                                                                                                        'o',
                                'f',
                                                                                                                                                                                                          ' ',
                              't',
                                                                                                                                                                                                            'e',
                            'c',
                                                                                                                                                                                                              'h',
                          'n',
                                                                                                                                                                                                                'i',
                        'c',
                                                                                                                                                                                                                  'a',
                      'l',
                                                                                                                                                                                                                    ' ',
                    'd',
                                                                                                                                                                                                                      'e',
                  'b',
                                                                                                                                                                                                                        't',
            }));
            yield return new ME_BREATHES_COPSINCYBERPUNK2077BYCDPROJEKTRED_Мусорщики___IHAVENOCLUEWHATTHEFUCKTHATMEANSBUTITSOUNDSCOOLAMIRITE(5f);
            DESCRIPTIVEMETHODNAMES_WHATARETHOSE_IDONTKNOWSHITABOUTTHOSELMAO("these signs look orderly, but i assure you that if you check the source code at github.com/extraes/BW-Chaos and look at Effects\\Misc\\ChesmondEffect.cs youll see a wonderful display of why-the-fuck-ery");
        }

    }

    
}