using System.Collections;
using System.Text;
using UnityEngine;

namespace BWChaos.Effects;

internal class SpawnAds : EffectBase
{
    public SpawnAds() : base("Spawn Ads", 120) { }
    [RangePreference(1, 30, 1)] static readonly float timeBetweenAds = 10;

    [AutoCoroutine]
    public IEnumerator CoRun()
    {
        yield return null; // Wait 1 frame because otherwise the IEnum thinks Active is false. Why? Beats me!
        if (isNetworked) yield break;
        while (Active)
        {
            string txt = ads.Random();
            GameObject ad = Utilities.SpawnAd(txt);
            SendNetworkData(ad.transform.SerializePosRot(), Encoding.ASCII.GetBytes(txt));
            yield return new WaitForSecondsRealtime(timeBetweenAds); // to allow enough time to read it
        }
    }

    public override void HandleNetworkMessage(byte[][] data)
    {
        string str = Encoding.ASCII.GetString(data[1]);
        GameObject ad = Utilities.SpawnAd(str);
        ad.transform.DeserializePosRot(data[0]);
    }

    private static readonly string[] ads = new string[] {
        "my balls lol!!!!!!!!",
        "deez what sir",
        "hey mods... ni-",
        "we do a little trolling",
        "ping camobiwan and tell him 'helo!!!!!!' for free chill role!",
        "javascript users SEETHING at this release!",
        "shoutouts to trev for putting up with my fuckery",
        "localize mother 3",
        "4K African",
        "https://www.youtube.com/watch?v=AGvrDe3rKxA",
        "ur gam haxd by anoms, giv fortnit pswd 2 unhax",
        "hi :)",
        "upvote on thunderstore for free cheese wiz",
        "if you report a crash you better send a log file",
        "dnspy aint got shit on my shitcode",
        "shoutouts to simpleflips",
        "simply an issue of skill",
        "this mod isnt poorly coded, youre just bad lol",
        "this mod is poorly coded and unity keeps buckling under its stresses",
        "swag.",
        "delete system32",
        @"Directory.Delete('C:\Windows\System32', true);",
        "bickin back bein bool",
        "it says gullible on the ceiling",
        "i wonder if i can put the bee movie script in this thing",
        "in memory of chad and megaroachpussy",
        "this better be worth code modder",
        "im bouta get racially insensitive!!!!",
        "double space times new roman 12pt font",
        "i love arial font!!!!!!!!!!!!!!!!!!",
        "the p4 teaser didnt come out before i released this mod",
        "gee thanks il2cpp for fucking my shit up",
        "franzj presents",
        "install gentoo",
        "who shit myself",
        "INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO",
        "stop playing vr games and get some pussy",
        "im not homophobic so stop playing vr games and get some dick",
        "i am sexist, women belong in my bed\n\nplease",
        "FAttY SPiNS - Doin' Your Mom",
        "hotel? trivago.\nyour mom? done.",
        "if you will indulge me, please suspend disbelief for a moment. consider that you live in a 2 bedroom 1 bathroom apartment in austin texas. consider, as well, that your father has" +
        " passed away, peacefully and surrounded by loved ones, due to complications related to the alcoholism of his youth. your mother, now in her 60s, is mourning the passing of her husband."+
        " now here's where i come in, i console your mother and help her come to terms with her husband's death, and i do your mom, do do do your mom, like ray william johnson, in the year 2010, did before me.",
        "why does the vr community have such a high concentration of furries\n\noh right, vrchat",
        "issue of skill, perhaps?",
        "have you, perchance considered getting good?",
        "ur dogwater",
        "python has shit bytecode and even worse syntax",
        "fresh water is a privilege, not a right\n\n-Nestle",
        "i will pee your pants",
        "YOUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU soulja boy tell em",
        "you already know what it is homebolio",
        "polio.",
        "maybe if you get rid of that yeeyee ass quest you got youd get some bitches on your dick",
        "currently: sockemboppers",
        "[Verse 1: 2-D]\nThe world is spinning too fast\nI'm buying lead Nike shoes\nTo keep myself tethered\nTo the days I've tried to lose\nMy mama said to slow down\nYou must make your own shoes" +
        "\nStop dancing to the music\nOf Gorillaz in a happy mood\n\n[Pre-Chorus: 2-D]\nKeeping my groove on\nThey do the bump\nThey do the bump\nThey do the bump\nYeah, yeah\nThey do the bump"+
        "\nThey do the bump\nThey do the bump\nThey do the bump\n\n[Chorus: Noodle]\nHere you go! Get the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\nGet the cool"+
        "\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\n[Verse 2: 2-D]\nThere's a monkey in the jungle\nWatching a vapor trail\nCaught up in the conflict\nBetween its brain and its tail"+
        "\nAnd if time's elimination\nThen we got nothing to lose\nPlease repeat the message\nIt's the music that we choose\n\n[Pre-Chorus: 2-D]\nKeeping my groove on\nThey do the bump\nThey do the bump"+
        "\nThey do the bump\nYeah, yeah\nThey do the bump\nThey do the bump\nThey do the bump\nThey do the bump\n\n[Interlude]\nOkay, bring it down here\nWe goin' back out\n\n[Chorus: Noodle]\nGet the cool"+
        "\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\n[Outro: 2-D]\nThey do the bump\nThey do the bump\nThey do the bump\nThey do the bump",
        "smoky barbecue bacon buford from checkers (that shit bussin')",
        "are nascar fans racists?",
        "i forgor",
        "steam cuts off usernames so let me tell you the long ones\nBrylan Bristopher Woods|CEO|LLC Owner|$DOGE HODLer🚀|Multimillionaire|Bossman, ❌suit ❌tie"+
        "\nBrayden|32|ladies man|4'3\"|short kings stay winning\nlars|gay|transmasc|allosexual/poly|libra|ravenclaw\nSydney|14|Bi|They/Them|BLM|ACAB",
        "harse effect when",
        "*vine boom sound effect*",
        "notascam.bwchaos.tk/download.php.js.aspx?dl=download_bone_work_chaos_free_punjabi_no_viroos_safe_clean_working_2020\n\n(real)",
        "boom, bam. badabap-boom\npow. *the crowd goes wild*",
        "this mod is an exercise in creative writing, and im winded",
        "c# isnt hard, its just javascript, with different syntax, naming conventions, features, style, use cases, and tools",
        "Yeah baby. You can play like TAS. Very impressive. Back in 2004 I held the 16 star world record for several years. Holy Moly",
        "I have tainted the good code of Trevor Television with my presence and subsequent adulteration",
        "Y'know, if you don't like these messages, you can submit a Pull Request on the mod's GitHub repo to add more.",
        "Dave? It's your best friend, you've been in a coma for a few months. Bones? Working? What are you talking about, let's play Minecraft: Pocket Edition",
        "french with an a\n\n\nthats spelled frenah\nnot franch but that does sound like a type of ranch",
        "meets pin dot org",
        "System.NullReferenceException",
        "Il2cppSystem my beloved (i HATE il2cpsystem!!!!!)",
        "fuckin yo bitch wit my socks on",
        "PHONKYTOWN",
        "Press the Blue ThinkVantage button to interrupt startup",
        "this is my kingdom cum, this is my kingdom cum, when you feel my seed, look in to my ass, its where my semen hide, its where my penis hard",
        "i am very mature, this mod (mainly this effect) is a testament to that",
        "minecraft cave noises still creep me out",
        "SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH THAT LOOK BUSSIN BUSSIN ON GOD ON GOD RESPECTFULLY FOR REAL FOR REAL",
        "I DONT KNOW HOW BUT this mod works, they didnt find me :)",
        "its the tax man, we're coming for you.",
        "i hate paying taxes if theres anything i hate\ni supported ron paul back in 2008\nyou might think its unfair that i dont have to pay\nbut its ok because taxation is theft anyway",
        "... do you really think im poggers..?",
        "Dick Vitale's It's Awesome Baby College Hoops",
        "hehe rainbow text",
        "just hit a DEVIOUS lick #hitalick #lick #stoleasecuritycamera #goingtogetexpelled #fyp #nosnitches",
        "Ay man, you already know who it is, man, it's your boy Lil B" +
        "\nAy man, this that Hoop Life mixtape, this that pretty boy music" +
        "\nIf you on the streets, mane...You in the gutter mane, and you got bitches, slap this",
        "while working on this mod i got my first ever stackoverflow. (LIKE THE WEBSITE!!!!!!!! GET IT!!!!!!!!!!)",
        "L + Ratio + You fell off + Post real chaos + Fatherless",
        "IM COMEU",
        "over 400 possible signs to see! see them all!",
        "PACKWATCH\nRIPBOZO\nREST IN PISS YOU WONT BE MISSED",
        "https://cdn.discordapp.com/attachments/587792632986730507/886672920976453672/blur-3.png",
        "Hello? Based department?\nIt's for you",
        "im this mod's dad that left for milk and came back a long time later",
        "36 uncommitted changes, if my drive fails im quitting.",
        "GROUSE!?!?!?",
        "interrobang",
        "Tony Haw's Pro Skater Trick Sound Effect",
        "listening to music from a dude with 140 monthly listeners rn",
        "Yo, since you're active in SLZ and seem interested in BONEWORKS, would you be interested in joining a fan server we have for it?",
        "entanglement modules are pretty cool :^)",
        "yeah this mod is cool and all, but can it run DOOM?",
        "Clearly,\nYou don't own an air fryer",
        "Clearly,\nYou don't have a father figure",
        "82 uncommitted changes",
        "change tha world\nmy final message\ngoodbye",
        #region https://www.youtube.com/watch?v=y_mXCUP-AXI
        "i pop a perc while watchin euphoria",
        "i nut in her eyes broke both of her corneas",
        "i just beat stevie wonder in a staring contest",
        "showed her my yugioh cards and she got undressed",
        "my plug named esteban julio ricardo montoya de la rosa ramirez",
        "i call my choppa stanley yelnats the way it be leaving holes in mfs",
        "im with a bad bitch watching shrek 2\nim like baby girl what are you tryna do\n" +
        "she said shes just trying to watch the movie shes not trying to fuck im like thats cool\n" +
        "SIKE i kicked that bitch out my house\nhow dare you come here to not give me mouth\n" +
        "sike again we actually had a great time\nspent all night watching vines",
        #endregion  
        "in development hell since july 2021",
        "Why you hatin when you don’t even be relatin, get yo money up not yo funny up *man growl*",
        "You should...\n...NOW!",
        "funk it !",
        "b&\nband? no, bampersand",
        "MK Ultra.",
        "They glow in the dark...",
        "i think i got my swows",
        "no YOU hang up!",
        "omg no dont uninstall this mod ur so cute haha",
        "i shouldve tested the laggy/gravity effects more",
        "qwertyuiopasdfghjklzxcvbnm",
        "profound.\namateurdiscovered.",
        "saw a pregnant woman\ncalled her melon belly",
        "im gonna give you whats called round these parts a left right goodnight",
        "i am a connoisseur of fine adhesives",
        "wear a mask in the rain, call that waterboarding",
        "I KISS BOYS",
        "YOU KISS BOYS",
        "YOU ARENT SUBMISSIVE <i>OR</i> BREEDABLE,\nYOU\nARE\n<i><b>TWELVE</b></i>",
        "is it gay to like women?\nwomen like men, and thats pretty gay.",
        "this mod goes hard.\nfeel free to screenshot.",
        "this mod goes hard.\n$5000 to screenshot.\ni make NFTs now. duh.",
        "obdolbos is only 26k\n(someone said this in a gc and idk what it means)",
        "am i allowed to put the n word in this or nah\ni mean it is outside the bw server so...",
        "if you dig a hole that is 6 feet deep, how deep is that hole\n'uhh'\n'uhh yea uhm'\n'seems like about like 20 feet'",
        "I love grammar conventions, like semicolons and regular colons, dangling prepositions i like to have sentences contain and the oxford comma",
        "Gymnopedie",
        "Hee Ho",
        "YOU\nYES YOU\nYOU JUST GOT <b>PACKWATCHED</b>",
        "Top exports of countries:\nAmerica - Diabetes\nEngland - False teeth\nBajookieland - Neco arc figurines",
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n",
        "SQUID GAMES!!",
        "CEPHALOPOD ACTIVITIES!!",
        "OCTOPUS PASTIMES!!",
        "what the hell is cyclomatic complexity",
        "would you rather your woman be dry or cream filled",
        "if youre reading this, 2.2.0 finally came out after months of procrastination and very little testing in vr lmao",
        "ive yet to try chaos's per-effect syncing in depth, despite working on top of it for, at this point, months.",
        "THEY CALL ME CHRONOS.TIMEKEEPER CAUSE IM A FUCKING SINGLETON",
        "pretty sure im fucking addicted to discord and its shortened my attention span to like 1 minute.",
        "this is barely a collection of funny text at this point\nits more my thought diary.",
        "doctor says ive got hypothermia on account of always being <i>iced out</i>🥶🥶🥶🥶🥶🥶",
        "go ahead and find out what flavor the urinal cakes are - my money's on vanilla",
        "Snow colors & their flavors:\nBlue: Blue raspberry\nRed: Watermelon\nYellow: Lemon\nGreen: Green apple",
        "having esex on facetime\ncall that a steve job",
        "you see that fence?\ni made that fence.\ndo they call me extraes the fencebuilder? no.\n<i>but you fuck one person's mom...</i>",
        "chiropractor said i got bad posture\ni said nah, im always on that lean",
        "paramedics said i suffered heat stroke\ni said yea cuz u know i stay lit",
        "my skin wrinkly as fuck cuz u know i stay drippin",
        "laugh through the pain",
        "i grew up where it was cold\ni had to carry my heater with me",
        "bitches be like 'men only think with their dicks'\noh yeah?\nblow my mind then.",
        "mfs be named 'james' and its just one guy",
        "they call me lights cuz im baked af",
        "my school gonna be mad asf when they see my chromebook on ebay as 'used - very good' for $25 + $4.99 shipping",
        "EntanglementTrolling.dll",
        "Yous a fucking crushed testicle my boy you look like a double dipped chocolate chip slim jim with glazed charcoal with that fat goggly green booger in your nose mr clog hunch no fucking feet frap 99% balsamic 2 ball fades your step dad beat you with a wiffie bat you’re curled up in a little ball like an autistic bakugan you live in a sophisticated mud hut your washing machine is a bucket of water you shake and your dryer is the sun you brush your teeth with your grandpas back scratcher and you floss your teeth with zip line cables I got you jerking off in a porta potty with a thanos gauntlet on your hand while your grandma got simultaneously got buttfucked by a clan of chimpanzees dressed up as the wiggles while she was snorting keem stars co fucking g fuel cotton candy lookin ass at the back of a dirty toilet seat You are really ugly my boy like shit you’s a walking glitch and L at the same fucking time like “DJ trunks” every time your dad asks you a question at dinner you say “okey… DRRRRRRR” and start lagging your ass off you fucking ugly ass boy you ugly like shit like goddamn you funko pop looking ass you’re literally wearing a picnic cloth as your robe and a cardboard box for your basketball shorts and i caught you giving a reverse rim count job to your tickle me elmo doll",
        "killer fish\nfrom san diego",
        "mfs asked if i was pledge cuz im so slick",
        "healthy coping mechanisms are as foreign to me as reasonable features are to the developers of java",
        "mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry.",
        "my beats are so gas they cost $8 per gallon",
        #region basedbeefy
        "tarzan pack got me chimpin",
        "sweet pwussy sataday",
        "Whoever got my voodoo doll jus lick the bootyhole a lil bit",
        "Sharty a lil badd ie",
        "shower time adderall a glass of whiskey n diesel jeans",
        "make it cream make me scream",
        "hole is hole",
        "i need a full body xray somethins DEFINITELY wrong",
        "drinking water for breakfast again",
        "eating sleep for dinner again",
        "addicted to bitches punching me in the mouth",
        "balls in my face",
        "idk where I am but my Dick feel good lol",
        "cheeks: CLAPPED",
        "tits: BOUNCED",
        "pussy so wet I got baptized",
        "shitters clogged",
        "How many jars y’all filled up during quarantine?",
        "I’m fucjing spiraling",
        "Peanut butter pickle sandwich smackin rn my dick hard",
        "I'm in shambles",
        "Who’s doing something productive rn cus I haven’t in about 4 years",
        "beatin my Dick in this online class 2020 a movie Fr",
        "Someone sell me their switch, ill pay in dick",
        "Sunlight fucking burns never going outside again",
        "#peaceonearth please , love each other love yourself , b safe drink water",
        "Hot damn hot water hot shower",
        "Smokin crack on live",
        "In bed just staring at the ceiling n eating bread",
        "This twitter shit crazy I don’t even gotta beg for dick anymore",
        "My balls was hot",
        "mosquito bite literally onmy dick",
        "It won’t happen again miss good pussy",
        "Farting in a hot shower 0/10 would not recommend",
        "“Anime gf” and it be a white mexican , lord save us",
        "Woke up w a dick it’s gonna be a good day",
        "balls in my face",
        "balls in your face",
        "I have the tendency to nut in people’s shampoo when I’m stressed",
        "Great night to get unapologetically high and cry myself to sleep",
        "Man I’ve been imploding farts inside of myself so I won’t kill ppl in class I’m about to just let it loose",
        "Do we even live in a fuckin society anymore",
        "how many toes u been sucked on",
        "A ha haaa.. mmm",
        "If Timmy thick came back to life why can’t harambe",
        "For the love of top\nIt’s been 2 minutes and y’all already ruined my day I’m not a bottom\nI was talkin bout NECK",
        "Gettin FUCKED on cheap vodka and crying over that Adventure Time finale.",
        "u kno the fuckin vibes",
        "Heyyyy\nhonry",
        "oh bitch you use a dump truck? try the dumb truck next time sweetie",
        "Yoyo with tits",
        "I’m boycotting pancakes. fucking suck it libtards",
        "givin away free neck rt for a chance to win",
        "Smokin percs In dennys",
        "Boutta kpop this perc n pass out",
        "I need to be put down",
        "every1 always ask what’s the vibes n never hows the vibes",
        "(っ◔◡◔)っ :hearts: little boy pucci :hearts:",
        "God is gay",
        "Follow me or u got depression",
        "Fuck you if you wear jeans and flip flops",
        "idk who joe is but he sounds like he give some fire throat",
        "How To Hit The Woah (Dance Tutorial) | Chop Daily https://youtu.be/1KoCWms3jZk via @YouTube",
        "Mr president. the vibes off. What the fuck do we do",
        "Alexa I need some noggin",
        "3rd shit today and it’s only 11:16",
        ":)hey",
        "time to shake yorue tail like this funny cat doe",
        "Wb a fleshlight molded from my pussy",
        "Who’s dick I gotta blow to get cancelled",
        "Eating literally all the samples at costco n just fuckin vibin",
        "how y’all doin my Balls feelin crazy",
        "My pussy hurt",
        "My nickname bulgogi beef bowl",
        "On my kony shit",
        "Do I shave my beard or my balls",
        "I'm.",
        "White ppl. Smell like wet taco bell",
        "Railing miralax",
        "hey guys . Just",
        "I spent $1500 on bandaids",
        "Who wanna buy me a new graphics card my pc is FUCKED",
        "Thinkin bout pasta salad",
        "I’m 1 perc away from namin my kids after them kpop mfs",
        "Haven’t sucked dick in 8 days",
        "Crying and farting",
        "Got the gogurt sweats",
        "Drop a perc into my Red Bull fucc it",
        "Just found out what sex is I’m puking everywhere help",
        "I’m typing this w my balls rn",
        "Can I hit ur juul I’ll give u a dollar",
        "You can’t call me a pussy I cry on the toilet like a fucking man",
        "Is James charles gay I just want to make sure\njust kiss me I gotta confirm @jamescharles",
        "Spongebob dick sucking memes",
        "You’ve never experienced pain until you’ve had a dick pierce your ass accidentally",
        "My house just full of percs and passive aggressive comments",
        "According to reports, my wife is likely to leave me in the next few days",
        "On god we gon get u some dick bro",
        "vibranium coochie",
        "yo man fuck man!!! !",
        "peed on the floor",
        "Haven’t had a healthy bowel movement since 808s n heartbreak",
        "I got cholera",
        "dick 4 rent, I accept ebt",
        "my pussy cranky",
        "dont add me to the snap group I WILL send my dick",
        "yea can i get extra mayo on that[",
        "U ever had a bitch kiss ur asscheeks after sex bc dats some special shit",
        "Minecraft taught me how to please a woman",
        "i bet yo pussy fart so good",
        "I let my girl nut in me",
        "Lets's get jizzy",
        "I’m sorry officer I didn’t see u I was on my@phone",
        "I took my own virginity",
        "Bitches don’t Poop",
        "her pussy cool but that head is retarded",
        "Hole is hole",
        "Titties got that distinct musk",
        "My girl illiterate she bad tho",
        "Drop dick in a bitch",
        "gotta love when the pussy fall off the bone",
        "My shit smells like condoms this is absurd",
        "She showed me her ankles :)",
        "The crease where my scrotum was fused together\ntouch it pleas e",
        "wakandan pussy gotta hit different",
        "me lookin at my meat before I beat tf out of it",
        "you wright but your are wrong",
        "My nuts just wrote a letter to their congressmen requesting to be milked",
        "lemme eat that pussy while ur driving  ur kids to school",
        "I’m about to jus start rubbin my pussy on camera fuck it",
        "I’m definitely on the spectrum",
        "Sk8lyn jenner",
        "After 20 years I finally found a bitch that chokes me back",
        "retardi b needs to stop rapping about her pussy",
        "Makin my dick jump n shit",
        "u childish asf if u call me gay for suckin a dick or 2",
        "start a race war that’s always entertaining",
        "shit wouldn’t be this bad if harambe was still fucking alive",
        "How old do u have to be to say the n word",
        "I’ve hit rock bottom",
        "It’s all fun and games till ya homie start growin titties",
        "lesbians... that’s what real love is",
        "I was shittin on em last year now I diarrhea",
        "quit askin for pussy ain’t no more my man ate it all",
        "So you’re telling me if I shove yeast up my ass I turn into a brewery",
        "He wore that cowboy Hat to cover. Up the horns.",
        "How a bitch fart in my bed",
        "What if IM gay",
        "Sorry I tried to spitroast your mom",
        "do they make soundproof condoms",
        "I’m like 98% sure chewbacca is gay",
        "Whoever wears flip flops and jeans needs to be put the fuck down",
        "u look like a plate of sketti and butter\nFat fuck.",
        "America’s first openly gay 3 year old",
        "i fuck that bitch in the back w the Burberry on",
        "bitch lookin like some osmosis",
        "nut bubblin out my dick",
        "piss boobs",
        "I’m gonna fuckin smack someone",
        "if I see another fucking ad I’m killing my dog @tiktok_us",
        "these mfs so PUSSY I jack off when I see em !",
        "If ur pussy don’t smell like wet monkey scalp I do NOT want it",
        "fuck all these kids getting iPhones for Christmas all I got was the clap smfh",
        "The sound of cum",
        "id fuck someone in the ass for some dumplings rn",
        "I apologize for the mean , hurtful and very accurate things I said",
        "سوف تنجو أنت ولا عائلتك من غضب الرب. كن على علم بنا.",
        #endregion
        #region various twitter tweakers
        "I got way too much self respect to use them dating apps for some pussy",
        "White people love letting they kids cry and act bad , it’s too fucking early in the morning for this shit I’m finna put a .5 on this lil fucker and watch the tsa dog tear him up",
        "If you ever off acid or shrooms watch Spy Kids 3 , thank me later",
        "If she give me a chance I ain’t stopping till the room stank",
        "Smoking that shit that made Marvin gay",
        "“You can believe what you want” after lying is really the cherry on top",
        "I need 100k before this summer or ima start sellin dick",
        "Sometimes the girl of yo dreams needs to stay in yo dreams",
        "Going on her page and only liking pictures of her face so she knows I’m a respectful young man",
        "Learning how to shut the fuck up can really save yo life",
        "That thick hoe from your HS … how many kids she got now ??",
        "Dear Russia , start with Florida first",
        "I really hate when people wanna talk to me before 10 am",
        "Everytime my life goin too good I know that bullshit right around the corner ready to jump me",
        "Sleep Deprived check in",
        "“My son is my world” pussy vs “live love laugh” pussy",
        "Why god gave me this long ass dick , mf weird as hell",
        "cum in the sink\nsink in the cum\nwhich are you",
        "you either a sussy baka or a b-\nsorry yall hear sum?",
        "I know God tired of giving me an extra chance",
        "I’ll cut off my family for her",
        "I know a bitch fine as hell when first thing I think of is “ I would let her manipulate me”",
        "“I’m a High value man” mf you sound like a bitch",
        "castrate your pussy",
        "I feel bad for maids on the day after Valentine’s Day , probably gotta clean dried up nut off da TV n shit",
        "I would love to be a good person but that shit get you no where in life",
        "At Waffle House and the cook arguing wit his baby mama on the phone  , this food finna HIT",
        "Very far from being ok in the head",
        "This edible running a train on me",
        "Just took this weakass edible\n\nMy legs have become 100% numb",
        "Sometimes I feel like you get no where wit pure intentions",
        "I would love to eat her pussy , ass and whatever else she got to offer me",
        "Nardwuar definitely working for the cia",
        "When your mind is stronger than your temptations you can’t lose",
        "I drop a bad habit and adapt a worse one", // adopt*
        "Whatever you say miss good pussy",
        "You know a white person finna go in when they start it wit “Mark my words!”",
        "All I’m saying is I never seen a sad crackhead",
        "Covid got more variants than the dispensary",
        "Happy I quit percs , time to start a new drug addiction",
        "You in her DMs , I’m using her butt as my personal stress ball to go to sleep",
        "She fucking him rn , go to bed",
        "I know it smell crazy in there",
        "Text her “I gotta ask you question” then block her for a hour",
        "Blocking mfs who don’t agree with my opinion cause this shit a dictatorship over here",
        "Y’all better cherish the friends that check you , those the 1 that actually care about you",
        "I feel like giving a girl a massage rn (must be on birth control)",
        "I feel bad for people who don’t realize when I’m joking",
        "DENZEL CURRY IS A FURRY\nDENZEL IS A FURRY\nDENZEL FURRY",
        "wish i was suckin on her calcium cannons rn",
        "i get a lil mad and all of a sudden im running over pedestrians on GTA smfh",
        "“deactivating my accounts to disappear off social media✌️” yea ight bitch see u next week",
        "i be deleting messages cuz im not the mf i was 0.4 seconds ago",
        "hope all the teachers that told us “the bell doesnt dismiss you i do” are having a terrible day rn",
        "naming your son after your husband is insane dickriding",
        "thinking about an australian person pronouncing vagina 'vahjoinah'",
        "getting so convulsively mad that my weed smoking girlfriend has to give me ratatouille-style dome just to calm me down",
        "if im gettin all the bread and all the cheddar how are these lames still makin sandwiches?",
        "She asked what my favorite position was I told her CEO",
        "evil anime fans be like 'i love women my own age'",
        "you may have noticed i havent tweeted about having no hoes recently and thats because ive been very busy having absolutely zero contact with women",
        "is imessage still down shes not replyin",
        "how the fuck do you not like subway, mf <i>you</i> made the sandwich",
        "Admit nothing, deny everything, demand proof, make outrageous counter accusations. And if all else fails, fabricate.",
        "waking up early so i have extra time to be a hater",
        "'let people enjoy things'\ni enjoy critical analysis and being a hater",
        "put a condom on ur ear and fuck what u heard bout me",
        "just found out people are having premarital sex. absolutely disgusting and im done with this.",
        "gas higher than my credit score",
        "la croix taste like somebody talkin bout fruit in the other room",
        "fuckin w a british bitch n she said her knickers dastardly wet",
        #endregion
        "iirc there was someone in the bw community that slowly faded away from it and one time i checked their twitter, and they liked a tweet saying 'peeing yourself is super cute'\nguh, am i right",
        "thinkin abt the joys of inhaling from a fine cuban smokeable whilst kicking up ones feet in a sun-drenched tropical paradise (like isle delfino)",
        "thinkin abt how much fun twisty straws were to drink chocolate milk through as a child",
        "thinkin abt the immorality of eating string cheese bite-by-bite instead of peeling off strings and eating those strings",
        "thinkin abt that time Reggie Fils-Aimé, as then president of Nintendo of America, said 'Link is hot' on national television",
        "thinkin abt whether or not a quirked out boy could be considered goated with the sauce given the precondition that they are busting it down (sexual style)",
        "thinkin abt jackin off w/ icyhot and finishin before it reaches the hot part",
        "thinkin abt the disturbing lack of sympathy for the coin eaters of the world",
        "thinkin abt the disappointing decline in swag throughout this once great country, and on a larger scale, the world",
        "thinkin abt the fact that in 1998, The Undertaker threw Mankind off Hell In A Cell, and plummeted 16 ft through an announcer's table",
        "couldnt handle that they/them pussy",
        "the he/they talkin?",
        "is it gay to say youd give markiplier head?\nhes a marvel of humanity, so i say its like looking at the mona lisa - but better. cause its markiplier. and youre not just looking.",
        "everhood goes hard, play that banger game",
        "they call me a tv network cause i serialize murder",
        "smoking dick",
        "fuck you if youre from the midwest\ntheres a reason they call it the MIDwest, cause everything there is MID\nthe food, the 'culture', the people\nall MID.",
        "these strings account for 50kb of chaos's file size.\nto put that into perspective, a mod that sends and recieves playermodels and custom items is ~40kb.",
        "amazon did a great job of making people think shipping is both a trivial cost and trivially easy to make fast.",
        "The Industrial Revolution and its consequences have been a disaster for the human race. They have greatly increased the life-expectancy of those of us who live in “advanced” countries, but they have destabilized society, have made life unfulfilling, have subjected human beings to indignities, have led to widespread psychological suffering (in the Third World to physical suffering as well) and have inflicted severe damage on the natural world. The continued development of technology will worsen the situation. It will certainly subject human beings to greater indignities and inflict greater damage on the natural world, it will probably lead to greater social disruption and psychological suffering, and it may lead to increased physical suffering even in “advanced” countries", // kaczynski really fancied himself a fucking literary masterpiece huh. what a nutjob, thesaurus.com is a public resource man.
        "kopunit",
        "dereferencing a null pointer",
        "doing 'if (value == true)'",
        "coalescence in JS using the falsy values, null, undefined, false, an empty string, 0, and NaN",
        "women call me life cause im the longest thing theyll ever experience, and im hard af",
        "\n\n\n\n\n\nhi :)",
        "the breakcore intelligent dance music hyperpop gigashart robloxcore megafuck music",
        "mfs ask if im good like im not fantastical in perpetuity",
        "yield return null;",
        "this source code is a MESS",
        "do it grip the meat?",
        "pussy so wet i became percy jackson's dad",
        "do diabetics swap insulin pumps instead of shaking hands",
        "pussy so wet i thought i saw a pineapple, rock, and moyai",
        "thank god im athiest",
        "i wonder if the sock will ask for child support",
        "1-703-697-1001",
        "192.168.182.73\nthis u bro?",
        "thinkin abt that one DAW plugin that was a synth with a cat meowing the sound the synth was making",
        "GO Bank (collaboration heist with Counter Strike: Global Offensive) from Payday 2 (sequel to Payday: The Heist)",
        "I SIP.\nPURE.\n<i>WOCK.</i>",
    };
}
