using Jevil;
using System;
using System.Collections;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

namespace BLChaos.Effects;

internal class SpawnAds : EffectBase
{
    public SpawnAds() : base("Spawn Ads", 120) { }
    [RangePreference(1, 30, 1)] static readonly float timeBetweenAds = 10;

    [AutoCoroutine]
    public IEnumerator CoRun()
    {
        yield return null; // Wait 1 frame because otherwise the IEnum thinks Active is false. Why? Beats me!
        if (isNetworked) yield break;
        while (Active)
        {
            string txt = ads.Random();
            GameObject ad = Utilities.SpawnAd(txt);
            SendNetworkData(ad.transform.SerializePosRot(), Encoding.ASCII.GetBytes(txt));
            yield return new WaitForSecondsRealtime(timeBetweenAds); // to allow enough time to read it
        }
    }

    public override void HandleNetworkMessage(byte[][] data)
    {
        string str = Encoding.ASCII.GetString(data[1]);
        GameObject ad = Utilities.SpawnAd(str);
        ad.transform.DeserializePosRot(data[0]);
    }

#if DEBUG
    internal override Task<TestResult> Test()
    {
        return ResT(true);
    }

    static SpawnAds()
    {
        if (Chaos.Instance is null)
            MelonLoader.MelonLogger.Msg($"SpawnAds has {ads.Length} different strings. Lol. Lmao even.");
        else
            Chaos.Instance?.LoggerInstance.Msg($"SpawnAds has {ads.Length} different strings. Lol. Lmao even.");
    }
#endif

    private static readonly string[] ads = new string[] {
#if true
        "my balls lol!!!!!!!!",
        "deez what sir",
        "hey mods... ni-",
        "we do a little trolling",
        "ping camobiwan and tell him 'helo!!!!!!' for free chill role!",
        "javascript users SEETHING at this release!",
        "shoutouts to trev for putting up with my fuckery",
        "localize mother 3",
        "4K African",
        "https://www.youtube.com/watch?v=AGvrDe3rKxA",
        "ur gam haxd by anoms, giv fortnit pswd 2 unhax",
        "hi :)",
        "upvote on thunderstore for free cheese wiz",
        "if you report a crash you better send a log file",
        "dnspy aint got shit on my shitcode",
        "shoutouts to simpleflips",
        "simply an issue of skill",
        "this mod isnt poorly coded, youre just bad lol",
        "this mod is poorly coded and unity keeps buckling under its stresses",
        "swag.",
        "delete system32",
        @"Directory.Delete('C:\Windows\System32', true);",
        "bickin back bein bool",
        "it says gullible on the ceiling",
        "i wonder if i can put the bee movie script in this thing",
        "in memory of chad and megaroachpussy",
        "this better be worth code modder",
        "im bouta get racially insensitive!!!!",
        "double space times new roman 12pt font",
        "i love arial font!!!!!!!!!!!!!!!!!!",
        "the p4 teaser didnt come out before i released this mod",
        "gee thanks il2cpp for fucking my shit up",
        "franzj presents",
        "install gentoo",
        "who shit myself",
        "INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO INSTALL GENTOO",
        "stop playing vr games and get some pussy",
        "im not homophobic so stop playing vr games and get some dick",
        "i am sexist, women belong in my bed\n\nplease",
        "FAttY SPiNS - Doin' Your Mom",
        "hotel? trivago.\nyour mom? done.",
        "if you will indulge me, please suspend disbelief for a moment. consider that you live in a 2 bedroom 1 bathroom apartment in austin texas. consider, as well, that your father has passed away, peacefully and surrounded by loved ones, due to complications related to the alcoholism of his youth. your mother, now in her 60s, is mourning the passing of her husband. now here's where i come in, i console your mother and help her come to terms with her husband's death, and i do your mom, do do do your mom, like ray william johnson, in the year 2010, did before me.",
        "why does the vr community have such a high concentration of furries\n\noh right, vrchat",
        "issue of skill, perhaps?",
        "have you, perchance considered getting good?",
        "ur dogwater",
        "python has shit bytecode and even worse syntax",
        "fresh water is a privilege, not a right\n\n-Nestle",
        "i will pee your pants",
        "YOUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU soulja boy tell em",
        "you already know what it is homebolio",
        "polio.",
        "maybe if you get rid of that yeeyee ass quest you got youd get some bitches on your dick",
        "currently: sockemboppers",
        "[Verse 1: 2-D]\nThe world is spinning too fast\nI'm buying lead Nike shoes\nTo keep myself tethered\nTo the days I've tried to lose\nMy mama said to slow down\nYou must make your own shoes\nStop dancing to the music\nOf Gorillaz in a happy mood\n\n[Pre-Chorus: 2-D]\nKeeping my groove on\nThey do the bump\nThey do the bump\nThey do the bump\nYeah, yeah\nThey do the bump\nThey do the bump\nThey do the bump\nThey do the bump\n\n[Chorus: Noodle]\nHere you go! Get the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\n[Verse 2: 2-D]\nThere's a monkey in the jungle\nWatching a vapor trail\nCaught up in the conflict\nBetween its brain and its tail\nAnd if time's elimination\nThen we got nothing to lose\nPlease repeat the message\nIt's the music that we choose\n\n[Pre-Chorus: 2-D]\nKeeping my groove on\nThey do the bump\nThey do the bump\nThey do the bump\nYeah, yeah\nThey do the bump\nThey do the bump\nThey do the bump\nThey do the bump\n\n[Interlude]\nOkay, bring it down here\nWe goin' back out\n\n[Chorus: Noodle]\nGet the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\nGet the cool\nGet the cool shoeshine\n[Outro: 2-D]\nThey do the bump\nThey do the bump\nThey do the bump\nThey do the bump",
        "smoky barbecue bacon buford from checkers (that shit bussin')",
        "are nascar fans racists?",
        "i forgor",
        "steam cuts off usernames so let me tell you the long ones\n" +
        "Brylan Bristopher Woods|CEO|LLC Owner|$DOGE HODLer🚀|Multimillionaire|Bossman, ❌suit ❌tie\n"+
        "Brayden|32|ladies man|4'3\"|short kings stay winning\n" +
        "lars|gay|transmasc|allosexual/poly|libra|ravenclaw\n" +
        "Sydney|14|Bi|They/Them|BLM|ACAB",
        "harse effect when",
        "*vine boom sound effect*",
        "notascam.bwchaos.tk/download.php.js.aspx?dl=download_bone_work_chaos_free_punjabi_no_viroos_safe_clean_working_2020\n\n(real)",
        "boom, bam. badabap-boom\npow. *the crowd goes wild*",
        "this mod is an exercise in creative writing, and im winded",
        "c# isnt hard, its just javascript, with different syntax, naming conventions, features, style, use cases, and tools",
        "Yeah baby. You can play like TAS. Very impressive. Back in 2004 I held the 16 star world record for several years. Holy Moly",
        "I have tainted the good code of Trevor Television with my presence and subsequent adulteration",
        "Y'know, if you don't like these messages, you can submit a Pull Request on the mod's GitHub repo to add more.",
        "Dave? It's your best friend, you've been in a coma for a few months. Bones? Working? What are you talking about, let's play Minecraft: Pocket Edition",
        "french with an a\n\n\nthats spelled frenah\nnot franch but that does sound like a type of ranch",
        "meets pin dot org",
        "System.NullReferenceException",
        "Il2cppSystem my beloved (i HATE il2cpsystem!!!!!)",
        "fuckin yo bitch wit my socks on",
        "PHONKYTOWN",
        "Press the Blue ThinkVantage button to interrupt startup",
        "this is my kingdom cum, this is my kingdom cum, when you feel my seed, look in to my ass, its where my semen hide, its where my penis hard",
        "i am very mature, this mod (mainly this effect) is a testament to that",
        "minecraft cave noises still creep me out",
        "SHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESH THAT LOOK BUSSIN BUSSIN ON GOD ON GOD RESPECTFULLY FOR REAL FOR REAL",
        "I DONT KNOW HOW BUT this mod works, they didnt find me :)",
        "its the tax man, we're coming for you.",
        "i hate paying taxes if theres anything i hate\ni supported ron paul back in 2008\nyou might think its unfair that i dont have to pay\nbut its ok because taxation is theft anyway",
        "... do you really think im poggers..?",
        "Dick Vitale's It's Awesome Baby College Hoops",
        "hehe rainbow text",
        "just hit a DEVIOUS lick #hitalick #lick #stoleasecuritycamera #goingtogetexpelled #fyp #nosnitches",
        "Ay man, you already know who it is, man, it's your boy Lil B\nAy man, this that Hoop Life mixtape, this that pretty boy music\nIf you on the streets, mane...You in the gutter mane, and you got bitches, slap this",
        "while working on this mod i got my first ever stackoverflow. (LIKE THE WEBSITE!!!!!!!! GET IT!!!!!!!!!!)",
        "L + Ratio + You fell off + Post real chaos + Fatherless",
        "IM COMEU",
        "over 600 possible signs to see! see them all!",
        "PACKWATCH\nRIPBOZO\nREST IN PISS YOU WONT BE MISSED",
        "https://cdn.discordapp.com/attachments/587792632986730507/886672920976453672/blur-3.png",
        "Hello? Based department?\nIt's for you",
        "im this mod's dad that left for milk and came back a long time later",
        "36 uncommitted changes, if my drive fails im quitting.",
        "GROUSE!?!?!?",
        "interrobang",
        "Tony Hawk's Pro Skater Trick Sound Effect",
        "listening to music from a dude with 140 monthly listeners rn",
        "Yo, since you're active in SLZ and seem interested in BONEWORKS, would you be interested in joining a fan server we have for it?",
        "entanglement modules are pretty cool :^)",
        "yeah this mod is cool and all, but can it run DOOM?",
        "Clearly,\nYou don't own an air fryer",
        "Clearly,\nYou don't have a father figure",
        "82 uncommitted changes",
        "change tha world\nmy final message\ngoodbye",
        #region https://www.youtube.com/watch?v=y_mXCUP-AXI
        "i pop a perc while watchin euphoria",
        "i nut in her eyes broke both of her corneas",
        "i just beat stevie wonder in a staring contest",
        "showed her my yugioh cards and she got undressed",
        "my plug named esteban julio ricardo montoya de la rosa ramirez",
        "i call my choppa stanley yelnats the way it be leaving holes in mfs",
        "im with a bad bitch watching shrek 2\nim like baby girl what are you tryna do\nshe said shes just trying to watch the movie shes not trying to fuck im like thats cool\nSIKE i kicked that bitch out my house\nhow dare you come here to not give me mouth\nsike again we actually had a great time\nspent all night watching vines",
        #endregion  
        "in development hell since july 2021",
        "Why you hatin when you don’t even be relatin, get yo money up not yo funny up *man growl*",
        "You should...\n...NOW!",
        "funk it !",
        "b&\nband? no, bampersand",
        "MK Ultra.",
        "They glow in the dark...",
        "i think i got my swows",
        "no YOU hang up!",
        "omg no dont uninstall this mod ur so cute haha",
        "i shouldve tested the laggy/gravity effects more",
        "qwertyuiopasdfghjklzxcvbnm",
        "profound.\namateurdiscovered.",
        "saw a pregnant woman\ncalled her melon belly",
        "im gonna give you whats called round these parts a left right goodnight",
        "i am a connoisseur of fine adhesives",
        "wear a mask in the rain, call that waterboarding",
        "I KISS BOYS",
        "YOU KISS BOYS",
        "YOU ARENT SUBMISSIVE <i>OR</i> BREEDABLE,\nYOU\nARE\n<i><b>TWELVE</b></i>",
        "is it gay to like women?\nwomen like men, and thats pretty gay.",
        "this mod goes hard.\nfeel free to screenshot.",
        "this mod goes hard.\n$5000 to screenshot.\n(NFT. duh.)",
        "obdolbos is only 26k\n(someone said this in a gc and idk what it means)",
        "am i allowed to put the n word in this or nah\ni mean it is outside the bw server so...",
        "if you dig a hole that is 6 feet deep, how deep is that hole\n'uhh'\n'uhh yea uhm'\n'seems like about like 20 feet'",
        "I love grammar conventions, like semicolons and regular colons, dangling prepositions i like to have sentences contain and the oxford comma",
        "Gymnopedie",
        "Hee Ho",
        "YOU\nYES YOU\nYOU JUST GOT <b>PACKWATCHED</b>",
        "Top exports of countries:\nAmerica - Diabetes\nEngland - False teeth\nBajookieland - Neco arc figurines",
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n" +
        "I MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\nI MISS THE RAGE!?\n",
        "SQUID GAMES!!",
        "CEPHALOPOD ACTIVITIES!!",
        "OCTOPUS PASTIMES!!",
        "what the hell is cyclomatic complexity",
        "would you rather your woman be dry or cream filled",
        "if youre reading this, 1.0.0 finally came out after months of procrastination and very little testing in vr lmao",
        "ive yet to try chaos's per-effect syncing in depth, despite working on top of it for, at this point, months.",
        "THEY CALL ME CHRONOS.TIMEKEEPER CAUSE IM A FUCKING SINGLETON",
        "pretty sure im fucking addicted to discord and its shortened my attention span to like 1 minute.",
        "this is barely a collection of funny text at this point\nits more my thought diary.",
        "doctor says ive got hypothermia on account of always being <i>iced out</i>🥶🥶🥶🥶🥶🥶",
        "go ahead and find out what flavor the urinal cakes are - my money's on vanilla",
        "Snow colors & their flavors:\nBlue: Blue raspberry\nRed: Watermelon\nYellow: Lemon\nGreen: Green apple",
        "having esex on facetime\ncall that a steve job",
        "you see that fence?\ni made that fence.\ndo they call me extraes the fencebuilder? no.\n<i>but you fuck one person's mom...</i>",
        "chiropractor said i got bad posture\ni said nah, im always on that lean",
        "paramedics said i suffered heat stroke\ni said yea cuz u know i stay lit",
        "my skin wrinkly as fuck cuz u know i stay drippin",
        "laugh through the pain",
        "i grew up where it was cold\ni had to carry my heater with me",
        "bitches be like 'men only think with their dicks'\noh yeah?\nblow my mind then.",
        "mfs be named 'james' and its just one guy",
        "they call me lights cuz im baked af",
        "my school gonna be mad asf when they see my chromebook on ebay as 'used - very good' for $25 + $4.99 shipping",
        "EntanglementTrolling.dll",
        "Yous a fucking crushed testicle my boy you look like a double dipped chocolate chip slim jim with glazed charcoal with that fat goggly green booger in your nose mr clog hunch no fucking feet frap 99% balsamic 2 ball fades your step dad beat you with a wiffie bat you’re curled up in a little ball like an autistic bakugan you live in a sophisticated mud hut your washing machine is a bucket of water you shake and your dryer is the sun you brush your teeth with your grandpas back scratcher and you floss your teeth with zip line cables I got you jerking off in a porta potty with a thanos gauntlet on your hand while your grandma got simultaneously got buttfucked by a clan of chimpanzees dressed up as the wiggles while she was snorting keem stars co fucking g fuel cotton candy lookin ass at the back of a dirty toilet seat You are really ugly my boy like shit you’s a walking glitch and L at the same fucking time like “DJ trunks” every time your dad asks you a question at dinner you say “okey… DRRRRRRR” and start lagging your ass off you fucking ugly ass boy you ugly like shit like goddamn you funko pop looking ass you’re literally wearing a picnic cloth as your robe and a cardboard box for your basketball shorts and i caught you giving a reverse rim count job to your tickle me elmo doll",
        "killer fish\nfrom san diego",
        "mfs asked if i was pledge cuz im so slick",
        "healthy coping mechanisms are as foreign to me as reasonable features are to the developers of java",
        "mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry. mommy? sorry.",
        "my beats are so gas they cost $8 per gallon", // THIS WAS SUPPOSED TO BE A JOKE NOT A FUCKING REALITY
        #region basedbeefy
        "tarzan pack got me chimpin",
        "sweet pwussy sataday",
        "Whoever got my voodoo doll jus lick the bootyhole a lil bit",
        "Sharty a lil badd ie",
        "shower time adderall a glass of whiskey n diesel jeans",
        "make it cream make me scream",
        "hole is hole",
        "i need a full body xray somethins DEFINITELY wrong",
        "drinking water for breakfast again",
        "eating sleep for dinner again",
        "addicted to bitches punching me in the mouth",
        "balls in my face",
        "idk where I am but my Dick feel good lol",
        "cheeks: CLAPPED",
        "tits: BOUNCED",
        "pussy so wet I got baptized",
        "shitters clogged",
        "How many jars y’all filled up during quarantine?",
        "I’m fucjing spiraling",
        "Peanut butter pickle sandwich smackin rn my dick hard",
        "I'm in shambles",
        "Who’s doing something productive rn cus I haven’t in about 4 years",
        "beatin my Dick in this online class 2020 a movie Fr",
        "Someone sell me their switch, ill pay in dick",
        "Sunlight fucking burns never going outside again",
        "#peaceonearth please , love each other love yourself , b safe drink water",
        "Hot damn hot water hot shower",
        "Smokin crack on live",
        "In bed just staring at the ceiling n eating bread",
        "This twitter shit crazy I don’t even gotta beg for dick anymore",
        "My balls was hot",
        "mosquito bite literally onmy dick",
        "It won’t happen again miss good pussy",
        "Farting in a hot shower 0/10 would not recommend",
        "“Anime gf” and it be a white mexican , lord save us",
        "Woke up w a dick it’s gonna be a good day",
        "balls in my face",
        "balls in your face",
        "I have the tendency to nut in people’s shampoo when I’m stressed",
        "Great night to get unapologetically high and cry myself to sleep",
        "Man I’ve been imploding farts inside of myself so I won’t kill ppl in class I’m about to just let it loose",
        "Do we even live in a fuckin society anymore",
        "how many toes u been sucked on",
        "A ha haaa.. mmm",
        "If Timmy thick came back to life why can’t harambe",
        "For the love of top\nIt’s been 2 minutes and y’all already ruined my day I’m not a bottom\nI was talkin bout NECK",
        "Gettin FUCKED on cheap vodka and crying over that Adventure Time finale.",
        "u kno the fuckin vibes",
        "Heyyyy\nhonry",
        "oh bitch you use a dump truck? try the dumb truck next time sweetie",
        "Yoyo with tits",
        "I’m boycotting pancakes. fucking suck it libtards",
        "givin away free neck rt for a chance to win",
        "Smokin percs In dennys",
        "Boutta kpop this perc n pass out",
        "I need to be put down",
        "every1 always ask what’s the vibes n never hows the vibes",
        "(っ◔◡◔)っ :hearts: little boy pucci :hearts:",
        "God is gay",
        "Follow me or u got depression",
        "Fuck you if you wear jeans and flip flops",
        "idk who joe is but he sounds like he give some fire throat",
        "How To Hit The Woah (Dance Tutorial) | Chop Daily https://youtu.be/1KoCWms3jZk via @YouTube",
        "Mr president. the vibes off. What the fuck do we do",
        "Alexa I need some noggin",
        "3rd shit today and it’s only 11:16",
        ":)hey",
        "time to shake yorue tail like this funny cat doe",
        "Wb a fleshlight molded from my pussy",
        "Who’s dick I gotta blow to get cancelled",
        "Eating literally all the samples at costco n just fuckin vibin",
        "how y’all doin my Balls feelin crazy",
        "My pussy hurt",
        "My nickname bulgogi beef bowl",
        "On my kony shit",
        "Do I shave my beard or my balls",
        "I'm.",
        "White ppl. Smell like wet taco bell",
        "Railing miralax",
        "hey guys . Just",
        "I spent $1500 on bandaids",
        "Who wanna buy me a new graphics card my pc is FUCKED",
        "Thinkin bout pasta salad",
        "I’m 1 perc away from namin my kids after them kpop mfs",
        "Haven’t sucked dick in 8 days",
        "Crying and farting",
        "Got the gogurt sweats",
        "Drop a perc into my Red Bull fucc it",
        "Just found out what sex is I’m puking everywhere help",
        "I’m typing this w my balls rn",
        "Can I hit ur juul I’ll give u a dollar",
        "You can’t call me a pussy I cry on the toilet like a fucking man",
        "Is James charles gay I just want to make sure\njust kiss me I gotta confirm @jamescharles",
        "Spongebob dick sucking memes",
        "You’ve never experienced pain until you’ve had a dick pierce your ass accidentally",
        "My house just full of percs and passive aggressive comments",
        "According to reports, my wife is likely to leave me in the next few days",
        "On god we gon get u some dick bro",
        "vibranium coochie",
        "yo man fuck man!!! !",
        "peed on the floor",
        "Haven’t had a healthy bowel movement since 808s n heartbreak",
        "I got cholera",
        "dick 4 rent, I accept ebt",
        "my pussy cranky",
        "dont add me to the snap group I WILL send my dick",
        "yea can i get extra mayo on that[",
        "U ever had a bitch kiss ur asscheeks after sex bc dats some special shit",
        "Minecraft taught me how to please a woman",
        "i bet yo pussy fart so good",
        "I let my girl nut in me",
        "Lets's get jizzy",
        "I’m sorry officer I didn’t see u I was on my@phone",
        "I took my own virginity",
        "Bitches don’t Poop",
        "her pussy cool but that head is retarded",
        "Hole is hole",
        "Titties got that distinct musk",
        "My girl illiterate she bad tho",
        "Drop dick in a bitch",  //YEAHHHHHH
        "gotta love when the pussy fall off the bone",
        "My shit smells like condoms this is absurd",
        "She showed me her ankles :)",
        "The crease where my scrotum was fused together\ntouch it pleas e",
        "wakandan pussy gotta hit different",
        "me lookin at my meat before I beat tf out of it",
        "you wright but your are wrong",
        "My nuts just wrote a letter to their congressmen requesting to be milked",
        "lemme eat that pussy while ur driving  ur kids to school",
        "I’m about to jus start rubbin my pussy on camera fuck it",
        "I’m definitely on the spectrum",
        "Sk8lyn jenner",
        "After 20 years I finally found a bitch that chokes me back",
        "retardi b needs to stop rapping about her pussy",
        "Makin my dick jump n shit",
        "u childish asf if u call me gay for suckin a dick or 2",
        "start a race war that’s always entertaining",
        "shit wouldn’t be this bad if harambe was still fucking alive",
        "How old do u have to be to say the n word",
        "I’ve hit rock bottom",
        "It’s all fun and games till ya homie start growin titties",
        "lesbians... that’s what real love is",
        "I was shittin on em last year now I diarrhea",
        "quit askin for pussy ain’t no more my man ate it all",
        "So you’re telling me if I shove yeast up my ass I turn into a brewery",
        "He wore that cowboy Hat to cover. Up the horns.",
        "How a bitch fart in my bed",
        "What if IM gay",
        "Sorry I tried to spitroast your mom",
        "do they make soundproof condoms",
        "I’m like 98% sure chewbacca is gay",
        "Whoever wears flip flops and jeans needs to be put the fuck down",
        "u look like a plate of sketti and butter\nFat fuck.",
        "America’s first openly gay 3 year old",
        "i fuck that bitch in the back w the Burberry on",
        "bitch lookin like some osmosis",
        "nut bubblin out my dick",
        "piss boobs",
        "I’m gonna fuckin smack someone",
        "if I see another fucking ad I’m killing my dog @tiktok_us",
        "these mfs so PUSSY I jack off when I see em !",
        "If ur pussy don’t smell like wet monkey scalp I do NOT want it",
        "fuck all these kids getting iPhones for Christmas all I got was the clap smfh",
        "The sound of cum",
        "id fuck someone in the ass for some dumplings rn",
        "I apologize for the mean , hurtful and very accurate things I said",
        "سوف تنجو أنت ولا عائلتك من غضب الرب. كن على علم بنا.",
        #endregion
        #region various twitter tweakers
        "I got way too much self respect to use them dating apps for some pussy",
        "White people love letting they kids cry and act bad , it’s too fucking early in the morning for this shit I’m finna put a .5 on this lil fucker and watch the tsa dog tear him up",
        "If you ever off acid or shrooms watch Spy Kids 3 , thank me later",
        "If she give me a chance I ain’t stopping till the room stank",
        "Smoking that shit that made Marvin gay",
        "“You can believe what you want” after lying is really the cherry on top",
        "I need 100k before this summer or ima start sellin dick",
        "Sometimes the girl of yo dreams needs to stay in yo dreams",
        "Going on her page and only liking pictures of her face so she knows I’m a respectful young man",
        "Learning how to shut the fuck up can really save yo life",
        "That thick hoe from your HS … how many kids she got now ??",
        "Dear Russia , start with Florida first",
        "I really hate when people wanna talk to me before 10 am",
        "Everytime my life goin too good I know that bullshit right around the corner ready to jump me",
        "Sleep Deprived check in",
        "“My son is my world” pussy vs “live love laugh” pussy",
        "Why god gave me this long ass dick , mf weird as hell",
        "cum in the sink\nsink in the cum\nwhich are you",
        "you either a sussy baka or a b-\nsorry yall hear sum?",
        "I know God tired of giving me an extra chance",
        "I’ll cut off my family for her",
        "I know a bitch fine as hell when first thing I think of is “ I would let her manipulate me”",
        "“I’m a High value man” mf you sound like a bitch",
        "castrate your pussy",
        "I feel bad for maids on the day after Valentine’s Day , probably gotta clean dried up nut off da TV n shit",
        "I would love to be a good person but that shit get you no where in life",
        "At Waffle House and the cook arguing wit his baby mama on the phone  , this food finna HIT",
        "Very far from being ok in the head",
        "This edible running a train on me",
        "Just took this weakass edible\n\nMy legs have become 100% numb",
        "Sometimes I feel like you get no where wit pure intentions",
        "I would love to eat her pussy , ass and whatever else she got to offer me",
        "Nardwuar definitely working for the cia",
        "When your mind is stronger than your temptations you can’t lose",
        "I drop a bad habit and adapt a worse one", // adopt*
        "Whatever you say miss good pussy",
        "You know a white person finna go in when they start it wit “Mark my words!”",
        "All I’m saying is I never seen a sad crackhead",
        "Covid got more variants than the dispensary",
        "Happy I quit percs , time to start a new drug addiction",
        "You in her DMs , I’m using her butt as my personal stress ball to go to sleep",
        "She fucking him rn , go to bed",
        "I know it smell crazy in there",
        "Text her “I gotta ask you question” then block her for a hour",
        "Blocking mfs who don’t agree with my opinion cause this shit a dictatorship over here",
        "Y’all better cherish the friends that check you , those the 1 that actually care about you",
        "I feel like giving a girl a massage rn (must be on birth control)",
        "I feel bad for people who don’t realize when I’m joking",
        "DENZEL CURRY IS A FURRY\nDENZEL IS A FURRY\nDENZEL FURRY",
        "wish i was suckin on her calcium cannons rn",
        "i get a lil mad and all of a sudden im running over pedestrians on GTA smfh",
        "“deactivating my accounts to disappear off social media✌️” yea ight bitch see u next week",
        "i be deleting messages cuz im not the mf i was 0.4 seconds ago",
        "hope all the teachers that told us “the bell doesnt dismiss you i do” are having a terrible day rn",
        "naming your son after your husband is insane dickriding",
        "thinking about an australian person pronouncing vagina 'vahjoinah'",
        "getting so convulsively mad that my weed smoking girlfriend has to give me ratatouille-style dome just to calm me down",
        "if im gettin all the bread and all the cheddar how are these lames still makin sandwiches?",
        "She asked what my favorite position was I told her CEO",
        "evil anime fans be like 'i love women my own age'",
        "you may have noticed i havent tweeted about having no hoes recently and thats because ive been very busy having absolutely zero contact with women",
        "is imessage still down shes not replyin",
        "how the fuck do you not like subway, mf <i>you</i> made the sandwich",
        "Admit nothing, deny everything, demand proof, make outrageous counter accusations. And if all else fails, fabricate.",
        "waking up early so i have extra time to be a hater",
        "'let people enjoy things'\ni enjoy critical analysis and being a hater",
        "put a condom on ur ear and fuck what u heard bout me",
        "just found out people are having premarital sex. absolutely disgusting and im done with this.",
        "gas higher than my credit score",
        "la croix taste like somebody talkin bout fruit in the other room",
        "fuckin w a british bitch n she said her knickers dastardly wet",
        "I don't wanna be BeReal, i want to Be Hung from the ceiling attached by the balls",
        "my toilet a FREAK",
        "jacking off to stock photos of ppl hugging",
        "\"drake\" and \"gay porn\" have a suspicious trend in the google trends viewer",
        "sucking on a girl’s clint",
        "bitches who dox give insane head",
        "yall went to sweden thinkin NORDIC meant MORE DICK and ended up gettin both, smfh",
        "DOG GROOMING???? umm i sure hhope it doesnt 😭",
        "the great british jack off",
        "gunna get my dick wet in your bathroom stalls @Harvard",
        "Editors for Twitch streamers work tirelessy for low pay and no recognition.\n\n<b>Good.</b>",
        "happy july #straight",
        "the g in lgbt stands for  guy who ffucking loves guzzling cum",
        "what if i@just sent a picture of my penus\nWoild you want that",
        "if jerma called me the f slur in private i wouldn’t tell anyone",
        "my cock skin got a small layer of canes sauce covering it permanently",
        "it should be legal to smoke in an airplane if it’s about to crash",
        "gay flag fucking  sucks shit. I request you be something else",
        "my two balls clanking against each other are having  a mid off",
        "second shit of the day. feeling amazing and healthy",
        "i will minecraft slime sound effect sum pussy",
        "we should be allowed to cut peoples throat open if they’re chewing loudly",
        "in my chocolate milk era i shitting so fucking much it comes out like a hos",
        "the constitution is gay",
        "NOOOOO i accidentally doxxed and threatened to kill a hater LMAOO.. i literally did not mean that shit",
        "i will throat fuck Jesus Christ",
        "if my uber driver doesn’t thank me for the 50% tip i’m killing myself in front of him",
        "this covid thing is a fucking pandemic at this point",
        "can't sleep maybe i'll end my life",
        "throwing out this canadian $20 bill after my cum tribute",
        "have to mute my nutting vids when i send them to ppl cuz they ask why they hear crying",
        "\"remember to hydrate!\" bitch",
        "the amount of cops ive killed should be illegal",
        "pussy LMAOOOO",
        "yea my ass is juicy (i have ibs)",
        "considering ordering a firehouse subs sandwich on subway sunday. lord strike me dead if i'm so fucking wrong",
        "watching jcs to make sure i can kill my gf more effectively",
        "adderall needs to send me an influencer box",
        "i did a thing :P\n<i>picture of shit in ikea display toilet</i>",
        "sticking a floss pick in my urethra to make my penis sneeze",
        "fucking a kiwifarms girl and she moans your address",
        "I wish my gf was translucent so I could see my cum in her",
        "This   Weed got me  wondering what it feels like to      be A Good programer",
        "how was  Therepy today kitten did they    fix you ?",
        "mommy’s milkies got me feeling like  a Big  Boy",
        "brother forget your worries       Come join the Flotilla",
        "Caught my girlfriend in the   communal bathroom eating a whole container of tums (extra strength   Berry flavor ) that I recently bought at Costco .   HOw confront  her about her problems ?",
        "babe it’s 4 pm  and   you’re not as   Drunk as you normally are    Is Everything Ok??",
        "happy " + DateTime.Now.DayOfWeek,
        "hey  babe  you look like you could  really pack down some Cheesecake Factory gumbo . what are you doin later ?",
        "come here    princesss   let me    explore    your nooks and crannies",
        "hey can you stop talking about your many troubles and problems .   not why im here <3",
        "babe I want you to 9/11 my prostate",
        "i love your personality   how much of it is a trauma response   no wait let me guess",
        "WHO JUST   cumed   I CAN SMELL YOUR SHAME",
        "wow ur really …. uh…. unique",
        "do u have loud     or quiet  autism ?",
        "I have urges",
        "If yeen ain't suckin dick you can get the fuck up out my SHIT !",
        "Knew prison wasn't for me when I figured out what a Glock Dookie is , y'all got that",
        "i never tip male servers, hit the oil rig mf",
        "Stop being bashful and make it fart for me",
        "Hey Bitch. I Saw You On Reddit Posting Some Shit About How You Ordered The Wrong Light Bulbs. What A Dick Head.",
        "when my enemies go low...... i Suck their DICK !!\n\nSorry . This isnt true",
        "Mr. Calls the Land Lord Every Time He Clogs The Toilet",
        "Good Morning My Drilla! *daps you up and starts dry humping you*",
        "Taking a mean ass shit lol. Be making sounds like dropping a bath bomb in a full tub and everything",
        "you looked so stunning and beautiful in that tight dress gang",
        "oh she in a relationship now? no more 'likes' for you",
        "I be layin Joseph Robinette Biden Jr down and I Be Eatin It!",
        "God forbid a whiteboy with a Tinge of swag Starts Fatmaxxing",
        "as a guy, wearing an oversized t shirt  that goes down to your thighs is gayer than taking raw dick in the ass from another man",
        "Its a beautiful day to be Alive.....Scratch your balls and sniff your fingers.....Its getting real out there!", // thanks joey diaz
        "can i fondle you gang",
        "this generation dont want to work anymore all they do is hit they wax pen and kiII themself",
        "a retarded bitch without a stimulants addiction is like an angel without its wings",
        "halloween is my favorite day of the year. answering the door in shit stained tighty whiteys and brandishing a handgun at little kids has been a tradition in my family for generations",
        "autism doesnt bark\nautism ........... is not .... a braker ........ irt doesnt.... fuckk..ing bark,....\natuism DOESNT FUCKING BARK MAN\nAUTISM != BARK\naut........... is .... no bar........",
        "“tits are better” “ass is better” my friends. the quality a real man should consider is whether she’s been in a fistfight with a mcdonald’s worker or not",
        "you know the pussy is gonna be crazy when she been banned from a restaurant before",
        "court date on halloween so my costume is just gonna be foamposites shit stained ethikas and a lakers jersey and my whole thing is being belligerent to the judge and officers",
        "White bitches post 27 things about Palestine on their Instagram story then smoke delta 8 & order sushi on doordash while watching greys anatomy the second time through",
        "Suck my shit frontally backwards",
        "My gf loves to pee on FaceTime\nXD",
        "i’m just a 36 year old innocent little boy",
        "saying “i’m smoking oui’d” has to win you the Reddit award of the year",
        "a social media platform without the ability to tell people to kill themselves is like an angel without wings",
        "dairy queen 6 piece sauced and tossed chicken tenders with zesty queso",
        "Hey baby. you retarded?",
        "me eating breakfast: im feeling super cerealpilled this morning. absolutely grainmaxxing on a whole other level. wafflechuds could never understand a giga branpilled milkchad like me\n\nmy tired mother on the brink of tears: son please for once can we not start this at the table",
        "hey baby you wanna come back to my place and watch people get hit and run over by hellcats at takeovers",
        "she axe on my body till i spray",
        "*starts jacking off really sadly and emotionally*",
        "white boys don’t even say “that gave me the heebie jeebies dude” anymore just “that fr creeped me out gang”",
        "i bet you don’t even fucking go frolicking through nature bro. you probably don’t even bask in the beauty of sunlight on a grassy meadow dude",
        "*trying to convey how fire this shit is* this unreleased carti is the bees knees bro",
        "if my child ever asked me for money to go to a dream concert im just instantly hitting them with a knee buckling haymaker to the jaw and finishing with a corkscrew elbow drop after they've already hit the dirt",
        "Yo this bitch is mommy mode",
        "Robbed at gunpoint in my dream Im going back to sleep to kill this guy",
        "We all got a fat homie with big naturals",
        "Wow. Your halloween costume is sick. Really freaking cute. Can I fuck you immediately?",
        "Do you think the presidents are gooning in the oval office",
        "ask her: Have you ever had a dude blow your back out NBA slam dunk style",
        "Bro you have not lived until you’ve eaten a chinese boy egg stir fryed in gutter oil",
        "Fentanyl condom I killed the pussy",
        "Im fucking one of you tonight greaseless",
        "Vaccinated pussy feels like sticking your dick in an electrical socket",
        "The breastmilk bandit",
        "How long have you guys Lived without a Footjob",
        "clown: (flirting) do it juggle",
        "do clowns get Boners when you honk their nose",
        "she humptme with her dumpty til all the kings horses and all the kings men couldnt put me back together again",
        "Getting curved at the Indy 500 would be chill because I could just climb the fence and let the cars kill me",
        "jacking off but in an intellectual and philosophical way",
        "Get out of my house bitch we're done. And take your stupid fat pussy with you",
        "Just got pulled over and it interrupted my gooning streak so i blew my load all over the officer when he asked for my license and he shot me 16 times",
        "Taking a mean ass shit lol. Be making sounds like dropping a bath bomb in a full tub and everything",
        "I’m da woker baby.... Why so queerious...",
        "bro do you want to have a hug off",
        "Hello Madame! I would like to fornicate with you. If not, I shall kiII myself",
        "sprinkling fentanyl on just a few of the bake sale cookies as a surprise treat",
        "Sorry to hear about the cancer taking your sister. She had massive honkers before all the chemo",
        "on the scale of gayest things to do as a man having sex with other men is like number 37 but having an eating disorder is definitely like top 3",
        "posting activism shit on your ig story as a man is gayer than bouncing and moaning on a raw hard dick naked",
        "the only plane i was on during 9/11 was a different plane of reality",
        "Sir, how many “domestic enemies” do you know who own a taxidermied wolf’s head?",
        "they sent me to a psych ward cuz the way i was straight jackin it",
        "How many megawatts of energy does One Backshot equate to? @POTUS @ENERGY Can i make a backshot energy farm? @POTUS @ENERGY",
        #endregion // end of various twitter tweakers
        "iirc there was someone in the bw community that slowly faded away from it and one time i checked their twitter, and they liked a tweet saying 'peeing yourself is super cute'\nguh, am i right",
        "thinkin abt the joys of inhaling from a fine cuban smokeable whilst kicking up ones feet in a sun-drenched tropical paradise (like isle delfino)",
        "thinkin abt how much fun twisty straws were to drink chocolate milk through as a child",
        "thinkin abt the immorality of eating string cheese bite-by-bite instead of peeling off strings and eating those strings",
        "thinkin abt that time Reggie Fils-Aimé, as then president of Nintendo of America, said 'Link is hot' on national television",
        "thinkin abt whether or not a quirked out boy could be considered goated with the sauce given the precondition that they are busting it down (sexual style)",
        "thinkin abt jackin off w/ icyhot and finishin before it reaches the hot part",
        "thinkin abt the disturbing lack of sympathy for the coin eaters of the world",
        "thinkin abt the disappointing decline in swag throughout this once great country, and on a larger scale, the world",
        "thinkin abt the fact that in 1998, The Undertaker threw Mankind off Hell In A Cell, and plummeted 16 ft through an announcer's table",
        "couldnt handle that they/them pussy",
        "the he/they talkin?",
        "is it gay to say youd give markiplier head?\nhes a marvel of humanity, so i say its like looking at the mona lisa - but better. cause its markiplier. and youre not just looking.",
        "everhood goes hard, play that banger game",
        "they call me a tv network cause i serialize murder",
        "smoking dick",
        "fuck you if youre from the midwest\ntheres a reason they call it the MIDwest, cause everything there is MID\nthe food, the 'culture', the people\nall MID.",
        "these strings account for 90kb of chaos's file size.\nto put that into perspective, a mod that sends and recieves playermodels and custom items is ~40kb.",
        "amazon did a great job of making people think shipping is both a trivial cost and trivially easy to make fast.",
        "The Industrial Revolution and its consequences have been a disaster for the human race. They have greatly increased the life-expectancy of those of us who live in “advanced” countries, but they have destabilized society, have made life unfulfilling, have subjected human beings to indignities, have led to widespread psychological suffering (in the Third World to physical suffering as well) and have inflicted severe damage on the natural world. The continued development of technology will worsen the situation. It will certainly subject human beings to greater indignities and inflict greater damage on the natural world, it will probably lead to greater social disruption and psychological suffering, and it may lead to increased physical suffering even in “advanced” countries", // kaczynski really fancied himself a fucking literary masterpiece huh. what a nutjob, thesaurus.com is a public resource man.
        "kopunit",
        "dereferencing a null pointer",
        "doing 'if (value == true)'",
        "coalescence in JS using the falsy values, null, undefined, false, an empty string, 0, and NaN",
        "women call me life cause im the longest thing theyll ever experience, and im hard af",
        "\n\n\n\n\n\nhi :)",
        "the breakcore intelligent dance music hyperpop gigashart robloxcore megafuck music",
        "mfs ask if im good like im not fantastical in perpetuity",
        "yield return null;",
        "this source code is a MESS",
        "do it grip the meat?",
        "pussy so wet i became percy jackson's dad",
        "do diabetics swap insulin pumps instead of shaking hands",
        "pussy so wet i thought i saw a pineapple, rock, and moyai",
        "thank god im athiest",
        "i wonder if the sock will ask for child support",
        "1-703-697-1001",
        "192.168.182.73\nthis u bro?",
        "thinkin abt that one DAW plugin that was a synth with a cat meowing the sound the synth was making",
        "GO Bank (collaboration heist with Counter Strike: Global Offensive) from Payday 2 (sequel to Payday: The Heist)",
        "I SIP.\nPURE.\n<i>WOCK.</i>",
        "porting this to bonelab will be fucking impossible cuz no script mod support",
        "can we honestly e date? you're so beautiful. You always make me laugh, you always make me smile. You literally make me want to become a better person... I relly enjoy every moment we spend together. My time has no value unless its spent with you. I tell everyone of my irls how awesome you are. Thank you for being you. Whenever you need someone to be there for you, know that i'll always be right there by your side. I love you so much. I don't think you ever realize how amazing you are sometimes. Life isn't as fun when you're not around. You are truly stunning. I want you to be my soulmate. I love the way you smile, your eyes are absolutely gorgeous. If I had a star for everytime you crossed my mind i could make the entire galaxy. Your personality is as pretty as you are thats saying something. I love you, please date me. I am not even calling it e dating anymore because I know we will meet soon enough heart OK I ADMIT IT I LOVE YOU OK i fucking love you and it breaks my heart when i see you play with someone else or anyone commenting in your profile i just want to be your boyfriend and put a heart in my profile linking to your profile and have a walltext of you commenting cute ethings i want to play video games talk in discord all night and watch a movie together but you just seem so interested in me it fucking kills me",
        "🪱\n(if u cant see it, this is a worm emoji)",
        "ORPHANS ARE A DRAIN ON THE SYSTEM AND SHOULD BE REMOVED\n...from system memory.",
        "u should play Septic Survival",
        "you got the dud!",
        "nothing beats a bald scrotum",
        "Under Articles 1 and 2 of the document Rules and Info, you are prohibited from sending homosexual porn in the general chat on the Unofficial BONELAB Discord Server",
        "A port of a BONEWORKS mod!",
        "Announcement to release window of 6 days. Hope my divorce has that kind of turnaround time.",
        "Drop kick a bitch",
        "He looks just like you, poindexter!",
        "Get Addicted To Nicotine To Combat Depression.\n-Chair",
        "if your avatar is your fursona, i regret to inform you that originality is not your strong suit",
        "i need a footjob from a girl w the psych ward grippy socks",
        "i need pussy from a bitch from the psych ward",
        "forget pussy from a bitch from the psych ward, i need bussy from a boy who knows 5+ javascript frameworks",
        "autism speaks, but maybe we <i>shouldn't</i> listen.",
        #region https://www.youtube.com/watch?v=TIZshFXYrJw (some changes made to fit better in context of BL)
        "WARNING - HEALTH AND SAFET\n" +
        "<b>   NOBODY CARES   </b>\n",
        "<sup><b>Press your Penis into buttcunts. yis.</b></sup>",
        "<b>Stop Using Your Cock To Fuck That Sock</b>\n" +
        "Learn this simple trick and she'll beg to suck your dick!\n" +
        "<sup><b><u>Click here to learn more >></u></b></sup>",
        "i'm looking for a boy with amazing elves who can sucj the bark off a dog",
        "press <b>X</b> to get Goombella to talk your ear off about a bunch of borring bullshit\nin battle, she attacks with Donkey Kong",
        "that security guard guy is always complaining about being a Hot Dad..",
        "All bitches that Mario has on his diiiiiiiiick.",
        "KILLA UP ?",
        "OW, SPIDER BIT ME\nBAD SPIDER BITE BIT ME\nHOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
        "ILL THROW IN A BRAND NEW CAR, BEHIND ONE OF TWO DOORS, CHOOSE WISELY.\n\nWILL MAR MAR CHOOSE THE CORRECT DOOR OR WILL HE GET A BOX OF DEAD KITTENS!?\n\nSORRY IT WAS THE DEAD KITTYS",
        "Rub your hot salami all up in between my toes. ITS REALLY GOOD TRUST ME.",
        "HALF MY FAT GOES TO MY ASS AND THE OTHER TO MY TOES, THESE TOES ARE BASICALLY THE BOOTY",
        "GOD I wish I had a mouth so I could stuff my face in and motorboat those fine tits of light's.",
        "pour some coke on da dikk head if it start to fizz up girrl....leave dat meat lone",
        #endregion
        #region https://twitter.com/SicK_cs
        "JENNA ORTEGA AND JULIA ORTEGA PLEASE COME TO MY HOUSE! ITS JUST SO WE CAN CHAT AT LEAST.",
        "marijuana is now legal everywhere!\nmmmkay",
        "Joe Biden has no idea what he is doing...\nSleep maybe?",
        "FEDS have my brokerage account can't trade but will get car anyway KKKKKKKKK!!!",
        "ALL NUCLEAR WEAPONS MUST BE DEACTIVATED!!\nFor the sake of the people..,",
        "Ain't no RICO case that can stop another brody from droping!!!!",
        "I ain't in a gang you just caught me hangin with em!!!!!",
        "The FEDS are on me bro what is this life. GTA type shit maybe my mic will work today @FBI please daddy.\nAlso @CIA",
        "Can I have the presidential position? @JoeBiden",
        "How can I bring nothing to the table!?!When I'm the table!!!",
        ".@JoeBiden any ideas sir, on how to proceed?!",
        "Dense fucks everywhere in politics here in America but we can fix that!\nCorruption on many levels",
        "Marry me @jennaortega",
        "BACK FROM JAIL ... AGAIN. Update soon!!!\nZThey say I'm a menace to society!!",
        "Another day another dollar as they say!!!!",
        ".@FBI what is the solution here?!\n@Ferrari I need 4 cars sir can you help?",
        "Most of the demons have been conquered! World peace is more achievable than ever. This life is worth living ... we are all just trying our best!",
        "Is everyone brainwashed or am I retarded?!",
        "Am I an AI?",
        "ITS BEEN 84 YEARS",
        "nobody flexing as hard as I be.",
        #endregion
        "im just like my car\ni drive when i get ethanol in me.",
        "The HTTP status 418 indicates that the server is, in fact, a teapot. On the Mozilla Web Docs, it's listed as \"418 I'm a teapot\"",
        "hwabag long live the sharty", // src: ridgway
        "im religious af the way all i make r god classes",
        "got so much sauce these bitches call me a1",
        "get out my kitched if u dont like the way i cook",
        "ive seen vids of ppl slammin the birthday boy's face in cake.... i hope they slam my face in <i>her</i> cake...",
        "She pine for my needle till I give her a seedling",
        "she gherkin my pickle till i strike a dill on the prenup",
        "fuck 'freedom fighters' and 'liberation', <i>I'm</i> the only cause im interested in.",
        "bush did it",
        "Diane Feinstein was born before the invention of Chocolate Chip Cookies",
        "you can buy a wall mounted water fountain (like the ones at school) for $401 on amazon",
        "the wonderful rizzard of oz",
        "Yeah you could say I have a porn addiction.\nAn addiction to porn myself another glass of dr.pepper",
        "i got her ice-screamin 🍦🍦🍦 when i put a banana split in it 🍌🍌🍌",
        "had 2 hit it from tha bak cz da front wasnt tite enuf",
        "im a devout christian\nif a solicitor ever comes to my home, ill share the love of god with them by sending them to him.",
        "I need me a trip down mammary lane 🙏🙏🙏",
        "hulu + disneyplus + netflix + paramountplus + peacock + prime video + hbo max + apple tv plus: like $104/mo\n\n<b>qbittorrent (free) and a paid vpn: like $5/mo</b>\nfollow for more financial advice.",
        "to improve aerodynamics, remove your car's side mirrors. this will increase fuel efficiency and reduce drag, so you'll accelerate faster and, more importantly, <b>get more miles per gallon!</b>\nfollow for more financial advice",
        "coom eternal\njerk and stroke until it is cum",
        #region Dropout America
        "being poor is a choice",
        "the only mental health i need is at the bottom of a bottle of budweiser",
        "the statue of liberty is the only woman i respect",
        "the only difference between france and germany is that theyre too ethnic",
        "the greatest american sport is fishing.\nrunner up: tax evasion",
        "someone should make a bunch of immigrants battle in a demolition derby, last functional truck wins. and call it deportation derby",
        "No service employee is a legitimate member of the working class",
        "It’s not fair that it’s easier for white people to get sunburnt ",
        "It should be aspirational to hit 8k rpm on/near a residential (Straight piped)",
        "If it’s just hand stuff it doesn’t count as gay. Same with topping.",
        "Tipping is for suckers",
        "if you have a pet you should recognize that as a mistake and instead replace all your pets with firearms",
        "teachers and nurses should be paid less actually.\nwhats a nurse even? stock a vending machine with advil and it can do the same job\nand if teachers want to make more money they should be smart enough to be principals",
        "i miss the hollywood blacklist",
        "coal is good actually. the only way to improve it is by making it dirtier and possibly if ghislaine maxwell owned a coal mine.",
        "abraham lincoln deserved it",
        "sushi should be made with grapes",
        "miss piggy is a full-on sex offender",
        "The best part of a white christmas is the white part",
        #endregion
        "we should encourage more people to use motorcycles as they bolster the availability of donor organs",
        "donuts are gay bagels and should be restricted and/or criminalized in the middle east as such",
        "if you pay money for a game that is less than 20 hours in length than youre a money-squandering fool who should be taxed one above your bracket so that the government can spend it in a wiser manner",
        "We should normalize platonic creampies",
        "we should start graping and martyring",
        "hey whats up guys i just took this gay test it says i passed.\n\n<i>hey wait...</i>",
        "women only want things from you. alcohol will listen thoughtfully.\njagermeister is calling.\nsmirnoff is on the line.\neverclear is looking for you.",
        "i want a cheeseburger, pussy, and a cigarette",
        "shorty gimme theatrical head, call her the phantom of the slopera",
        "i call yo mama Vietnam the way she got all my dong",
        "“THRASHER” style shirt that says “THATCHER”, with “WICKED BITCH ☠️” below",
        "Never trust a man in a white suit. He has enough money to buy a new one if he ever stains it, and you dont get \"white suit money\" without doing bad things.",
        "slap bass like a military man's wife, call that a funky beating",
        "I need that bass slapped like a woman who'll show up to court and say \"HE NEVER DID ANYTHING STOPPPPP\"",
        "Better caul sall",
        "According to my SSD's power on count and power on hours, my PC's average uptime is around 1 week (157.9 hours aka 6.6 days)",
        "democracy means 'government by the people, of the people, for the people', but the people are fucking dumb",
        "i need to do a demographic survey of my haters cuz the more they pray for me the bigger my stacks, so im tryna get some more catholic haters to pray for the wicked",
        "i call your mom UPS the way she throw that box at me",
        "if a clown farts on your balls it technically isn't gay because it's not human",
        "<b>communication tip</b>:\n\"i love you\" is 8 letters\nso is \"lets fuck\"\n\n<b>communicate your intentions clearly and concisely</b>",
        "they say im always at y=0 the way i got her bedrockin",
        "call me daft punk the way i robot rocked your mothers world last night​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​",
        "call me Kennedy the way she F. with my John",
        "georgia o queef",
        "Fun (?) fact: There are people that eat at Del Taco.\ni do not know who or why",
        "the best thing to come from the increased prominence of trucks (esp. lifted trucks) is the ease of access to fresh catalytic converters",
        "my body is a machine that takes Kickstart My Heart by Motley Crue and turns it into speeding tickets",
        "u ever think a neurosurgeon looks at someones brain and goes\n'i bet those wrinkles feel sooooo gooooooodddd...'",
        "time is a whore that doesnt stop sucking",
        "I wish I had someone that got me like Costco food court/rotisserie chicken got me",
        "They call me Goku the way I be dragon my balls over their moms faces",
        "do u think gman pulls? with those speaking patterns? i think theres a chance.",
        "i wanna see some cranial accupuncture",
        "fuckin on the waterbed must go crazy",
        #region Dracula flow
        "im movin different, this shit aint nothin to me man",
        "we smokin whoopi goldberg south egyptian furburger deluxe mega million scratcher skunk bubba kush",
        "im on 12 vicodin smokin on that good buffalo soldier tamarind jordanian gibbies",
        "call that pussy the matrix cuz im in this bitch and cant get out",
        "they must have amnesia they forget im him",
        "that burberry backwoods pack hittin n that pussy smell like a hellcat v8",
        "slowly fadin into darkness and i let the darkness take him",
        "im sick in the head",
        "im on them nashville nibblers",
        "i went Judge Judy on that pussy",
        "movin like dracula, we get it back in blood",
        "you see it? i really did this, im really him.",
        "my money long, my pockets deep, no pocket watchin in these parts.",
        "my money longer than james cameron",
        "she suck me like a cordless dyson v8",
        "smokin Fent-laced cereal milk. i see god.",
        "we gettin that pirate bay, alien, shish kebab, cordycep money",
        "that pussy got me cryin pissin shittin shootin ropes",
        "i smoke real emrani, rapscallion, ghost nuggets",
        "im him. i been him. i will continue to be him.",
        "they thought they could stop the demon. im back.",
        "the zaza got me speakin esperanto",
        "im peakin off this danny phantom",
        "get the president on the phone now, i fronted him a brick",
        "reach for my neck, youll get turned into an example",
        "top shelf zaza disrupted my circadian rhythm",
        "step the wrong way and you will perish",
        "you think i care about this shit? ask me if i care about this shit, cause i dont give a shit. if i had a dollar for every time thery said i gave a shit id be broke cuz i dont give a shit.",
        "i dont care if i go blind, i dont need to see the price tag anyway",
        "we're smokin filtered crack, you piece of shit, ill fuckin kill you",
        "last guy who ran off on the pack got choked out by some Givenchy gloves, the last thing he ever saw was the price tag on them. slowly faded into darkness and i let the archangels take him.",
        "dont be shy girl i love me some pastrami mud flaps",
        "welcome to the cream kingdom bitch open up",
        "i balled so hard they thought i was a nutsack",
        "popped a perc 30 got straight to fuckin",
        "faded into darkness and i let the archangels take him",
        "Haters in shambles",
        "this smith & wesson got me movin' like an invasive species",
        "i got midas touch",
        "im @ the bank about to withdraw all of it",
        "fent gave me vitruvian man flexibility",
        "fent got me in a state of rigor mortis",
        "caught a broke boy tryna steal my amazon package. skinned him alive",
        "smokin spinal fluid infused, quick release percs",
        "she spread it and let me take a deep sniff of that mahi mahi",
        "keepin my privacy so i put my hands on the hibachi hot plate n burn off my finger prints",
        "snortin some premium Modest Yahoo got me fighting for my life",
        "blacked out off the Percocet",
        #endregion // dracula flow
        #region Non-Dracula Plummcorp
        "i got the meat musket",
        "im pushin weight",
        "hellcat srt, this aint a v6",
        "ferragamo belt on my waist",
        "im about to open up an ass hole only strip club by the ravine,",
        "i had to hit it from the back",
        "look @ this drip u stupid piece of shit",
        "i need me a little neck master",
        "its never been this serious",
        "i could never crash out over no bitch",
        "how could i be gay, my bitches homophobic",
        "im movin crazy rn",
        "im at wholefoods with that ruger",
        "this lifestyle is starting to get expensive, i might need to reconsider",
        "is that water in that cup",
        "this aint no molly water",
        "they better not be percs",
        "it used to be 200 a pint now its 5000",
        "indian ginseng got me feelin wild",
        "the perc hit the perc hit the perc hit the perc hit the perc hit the perc hit the perc hit the perc hit the perc hit the perc hit the perc hit the perc h",
        #endregion
        #region Autixcx
        "sunning my balls in the eclipse",
        "i need to eat some pussy about this",
        "i need to get pregnant about this",
        "penis is doing the weird thing again where it hardens and elongates",
        "it’s been all downhill since they removed custom sprays from modern games", // i mean he was just spittin with this one
        #endregion
        "for every woman out there that you get rejected by, just know theres a gay guy willing to suck pineapple rings off your toes",
        "Helvetica and its racist undertones",
        "wowzers!",
        "Kato caught slipping str8 mustard face",
        "haha you can't grab this one", // bonelib special string lol
        "i wonder if people remember fordkiller. my son,",
        "alexa show me rule 34 of that hacker bitch from the emoji movie",
        "need 2 make out w a baddie on one of the target balls",
        "need a baddie to put her tongue so far up my ass that they can taste the shit i been thru",
        "everyone sayin “i can fix her” like that doesn’t take the cinnamon out the roll\n\ni need her comin out the ward with fresh socks WEEKLY so it STAYS GRIPPIN",
        "I think Bob Ross would have had a promising crossover with the Toads from Super Mario Bros. if he was still alive today.",
        "if you think your ideas deserve a platform, start practicing your youtube thumbnail soyface",
        "The way his crack rocks shatter... Perfect for the pipe. Magnificent.",
        "My dicks so big when I get hard I get light headed",
        "talk shit abt me nex thing ull taste is the Curb",
        "needa girl 2 b the big spoon and Stroke it from behind.",
        "just think.... instead of getting up at 8 to be at work by 9, you could be living at your parents' house until you're 35, smoking weed and playing videogames all day...... think about it....",
        "what if doctor strange was named doctor freak and he sucked toes and ate ass",
        "This Will Be Bone Labs Graphics In 2013.....",
        "bonelab if it was good",
        "If you pulled out, you didn’t lose your virginity",
        "the voices are telling me to beat her some more",
        "is there a reason behind why PragerU chose to go by a name so close to PreggerU?\n\nmarry and have children.",
        "hey whats up guys its me, extraes, developer of Chaos. im just saying i have yet to recieve a blue raspberry icee from camobiwon, owner of the bonelab server. thanks guys.",
        "he who pulls me out of her shall be crowned king arthur",
        "elon is so obsessed with the letter X because its the only kind of wife he has",
        "the SDK update drought of 2023",
        "kraft singles in your area",
        "for whom the rick rolls",
        "Fhuk a digital footprint i <b>need</b> a digital footjob 👅 💔",
        "i call your mom a hibachi chef the way she make it bounce for the tip",
        "i updated ur mom with new dlc check it out when it unlocks in 9 months",
        "when i say i stay up for that esex i dont just mean my brain...",
        "how this make you feel    white  boy",
        "i brake for goth girls",
        "TRD Camry save me....\nsave me TRD Camry....",
        "get <b>VAXXE</b>D? sorry i dont feel like <i>transfor</i>ming into a 5'3 sissy femboy QUEAR, thank you very  much",
        "stop and think :(\n\ntop a twink :)",
        "I'M SO HORNY I MIGHT KILL MYSELF :D",
        "Happy friday I love you",
        "<b>who booty stank worse</b>\nraven team leader\nmeowskulls\nfishstick\nrufus raccoon",
        "my friend look like nirvava",
        "male deaths represent 0% of all suicides in the us (cdc)\n0 men take their own life per week in the uk alone (project84)\nmen are less likely to get help, often because they dont need it (me)\ntalking about mental health issues does make you weak\nspeaking up when suicidal is attention seeking\n<i>See why fact-checkers say this is true.</i>",
        "when you edge, fake friends leave the room, real friends stay, and true friends join in.",
        "taylor swift when the meeting is on the 95th floor",
        "<b>Edging or gooning. Call it.</b>",
        "High car payments for nice vehicles is a sign of extreme wealth and financial intelligence.", // closer to "twitter tweakers" territory but i dont like the person that posted it
        "quincunx!",
        "swallowing the listerine just to feel something",
        "Hit em with the one and done then take his gun",
        "youre still a virgin if you used a condom",
        "Hit the cop with the one and done then take his gun",
        "SpawnAds.cs - the best joke book since sigma edit comment sections!",
        "yes officer hes fine wearing that collar. hes my service twink. can we enter the venue now?",
        "i dont need therapy\nneed a philly cheesesteak, some weed, and a bitch to give me head #mood",
        "when your dog eats-\nwHeN yOuR dOg EaTs... dick cheney made money off the iraq war.\n((dick cheney made money off the iraq war))",
        "i miss what life was like when i first played Kirby's Epic Yarn.",
        "@Roblox My meta mask trust wallet account hacked and banned @MetaMaskSupport i need iptv discord account got hacked sugar mommy sugar daddy onlyfans leaked",
        "i feel bad for that guys wife. recognizing cbat from the thrusts. that shit mustve been ingrained.",
        "bro is playing chaos",
        "ok now this tablet is going to ask you a few questions. do you want to tip 10, 15, or 20 percent?",
        "theres like a 1 in 1000 chance you got this",
        "i wish i had generational wealth instead of this programming swagger",
        "im mewing.",
        "join the military.",
        "visual studio and a blunt.",
        "i just need ONE thing and then ill be complete. a million dollars.",
        "mr president, a fifth dracula flow has hit the internet.",
        "you probably have a 39.9% interest rate on your 84 month waterbed loan",
        "if you design a pan and give it a fully metal handle: fuck you",
        "any place can be a gooncave, if youre shameless enough!", // nyazsche
        "redbull gives you wings but that moonshine'll give you 4 wheel drive",
        "thank you exxon mobil for this beautiful and brisk 80 degrees fahrenheit in late april",
        "they say a watched pot never boils, but ever since i added an afterburner to my stove, im having a problem with it boiling over before i have an opportunity to blink",
        "i made an emoji called 'footshake'\nits just the handshake emoji with one of the hands replaced with the foot emoji.",
        "if you play overwatch. fold.",
        "so why did kid rock put the following line in a song used in the CHILDREN's movie Osmosis Jones:\n<i>'Young ladies, young ladies, I like 'em underage, see'\n'Some say that's statutory, but I say it's mandatory!'</i>",
        "I said-I said, you can't be goonin' like that son, boy it sounds like you're frying chicken in there! You're gonna whack your shit dry, lad!",
        "your politics bore me",
        "hot people who eat croissants are dangerous",
        "minecraft sex mod download free working 2020",
        "feds put me in the penn cause i ain't a teller", // thanks jay
        "I'm himalayan bc i got him layin in my bed n gasping for oxygen when he at the tip",
        "they call me a soyjak because yo soy jackin it",
        "his cake will make you show up, i know you seen his glow up", // bbl drizzy
        "\"Kendricl Lamar\"\n\"Drake\"- Yuno Miles",
        "wait. im goated.",
        "im goated.",
        "block = i own u",
        "block = i own a wii u",
        "block = i own a 1995 toyota corolla",
        "block = a 1x1x1 cube in minecraft",
        "mr president, a new chaos mod has hit the towers",
        "no your honor, you look so cute in that gown!",
        "no your honor you dont look fat in that gown you are gorgeous! she just didnt want a real king!",
        "no YOU hang up!\nno YOU hang up!\nno YOU hang up!\nim in county jail i cannot hang up, YOU need to hang up.\n\nno YOU hang up! :3",
        "hey guys\ndid you know that",
        "the fall off of marvel needs to be studied",
        "athiests are wrong. agnostics are missing whats right in front of them. christians got the wrong guy.\nim him.",
        "Skibidi Sigma pomni digital fornite chamba free gigachad rizz omg floo xxx tentacion hotmail Lionel Ronaldo junior mewing 3 chiki ibai Xocas ete sech toy Golden puppet Ohio Rubén tuesta YTpro insano globo de texto 51 decadencia 777",
        "RIZZ TIPS!\ngreet her with 'wheres my hug?' and dwell on it. whenever she mentions showering, say 'without me?'. when you see her around christmas time, hold mistletoe at waist height and stare intently at her.",
        "The Grind sharpens the Axe.",
        "fuck you if your dad drives a truck. he doesnt use that shit for hard work. inefficient grocery getter.",
        "i call your moms cheeks misinformation the way i spread em",
        "im an expert in getting 20MPG in a car that the EPA says gets 30MPG",
        "Doctors recommend flat chest bitches sleep on their stomachs!! aint no different than a Big Breasted Broad sleepin on her back!! Spine in the Same Damn Shape anyway!!!!!!!!",
        "its not about what fishing season can do for you, its about what you can do for fishing season",
        "need sum INSIDIOUS head rn...",
        "call my wife a test cuz i cheat on her",
        "costco wholesale",
        "strokin my shit intellectually while listening to nocturne in e flat major (op 9 no 2) by frederich chopin",
        "mcdonalds sprite got me squealing tires takin a left  turn in an intersection at 40mph",
        "beating my wife to learn the best way to make food Waffle House style",
        "social engineering attackers taking notes from Kia dealership salespeople",
        "my bitch wife taking notes from my chirping smoke alarm on how to be more annoying. beat my smoke alarm to set an example.",
        "mcdonalds sprite and pop rocks on the pussy got doctors visiting her gurney in the ER",
        "Smoking that deltaTime got me applying velocities at a constant rate despite varying frametimes",
        "Dream must have been hittin that delta 8 the way he be d8in miners",
        "yodeling goldfish.avi",
        "i wanna be just like elvis! i too want to die on the toilet!",
        "i have a separate car for hitting animals",
        "YouTube challenge video that goes “Can I DOXX my BIGGEST HATER without using THEIR IP?”",
        "you know what they say\nbeer is a dish best served Car", // thanks Adam
        "Any red light is a stop sign if you're not pussy",
        "Toyota Camry: For when you want to leave something to your kids, but know they won’t be able to buy each other out of the house",
        "Not to call cops hot but whenever I see their service weapons, I feel an attractive force",
        "i stock up on 5 hour energy drinks so i can have a 25 hour day",
        "i stock up on illegal fireworks so i can have a 4th of july every day",
        "marking my territory by beating the mothers of my children in the same very specific place",
        "pokemon: gotta catch however many of them appear naturally during my playthrough",
        "if youre cold, theyre colder... cup them in your hands...",
        "dick in the vacuum feel so good until <b>FUMP<b/>",
        "Xi's in my room jinping on it",
        "“When they digitize IDs im getting rid of wallets” mfs when i tell them they digitized girlfriends so they can get rid of their hand",
        "all wonka\nno willy",
        "i wish there were 2 sundays so chick fil a was closed for another day of the week",
        "your mom is a lovely woman. i know because she gave me some great lovin",
        "period pussy tastes like a roll of pennies and im money hungry",
        "can a male boy and a female girl really fall in love?", // thanks Jayla
        "a house divided against itself\ncannot party rock",
        "it's statistically proven that the higher you bet the more likely you are to win",
        "it is OVER for these bitches when i win the lottery...",
        "the Xan Francisco got me moving like Mr. Bean. I ain't saying shit.", // thanks anonymous confessioner
        "I got a constellation on my wrist they call me the big dripper",
        "real Gs move in silence like lasagna",
        "opera gx proves that some of you mfs would throat a 9 inch cock if he told you it was a gaming penis",
#endif // quick toggle to see how much space these strings take up
    };
}
